import { RepoTaleStory } from '../types/story';
import { ExportOptions } from '../types/api';

export function generateMarkdownReadme(story: RepoTaleStory, options: ExportOptions): string {
  const user = options.githubUsername || 'username';
  const repo = options.repositoryName || story.meta.repoName.split('/').pop() || 'repo';

  let md = '';

  if (options.includeBadge) {
    md += `[![RepoTale Interactive Guide](https://img.shields.io/badge/RepoTale-Interactive_Tour-blue?style=for-the-badge&logo=compass)](https://${user}.github.io/${repo}/)\n\n`;
  }

  md += `# 🗺️ RepoTale Interactive Architecture: ${story.meta.repoName}\n\n`;
  md += `> ${story.meta.description || 'Interactive codebase walkthrough and architectural call graph.'}\n\n`;

  md += `**Primary Language:** \`${story.meta.primaryLanguage}\`  \n`;
  if (story.meta.frameworks && story.meta.frameworks.length > 0) {
    md += `**Frameworks & Libraries:** ${story.meta.frameworks.map(f => `\`${f}\``).join(', ')}  \n`;
  }
  md += `**Entrypoint:** \`${story.meta.entryPoint}\`\n\n`;

  if (options.includeMermaid) {
    md += `## 📊 System Call Graph\n\n\`\`\`mermaid\nflowchart TD\n`;
    story.callGraph.nodes.forEach(node => {
      const safeId = node.id.replace(/[:/.-]/g, '_');
      const label = node.label.replace(/"/g, "'");
      let icon = '🔧';
      if (node.type === 'entry') icon = '🚀';
      else if (node.type === 'middleware') icon = '🛡️';
      else if (node.type === 'service') icon = '⚙️';
      else if (node.type === 'data') icon = '💾';

      md += `  ${safeId}["${icon} ${label} (${node.type})"]\n`;
    });

    story.callGraph.edges.forEach(edge => {
      const s = edge.source.replace(/[:/.-]/g, '_');
      const t = edge.target.replace(/[:/.-]/g, '_');
      if (edge.label) {
        md += `  ${s} -->|"${edge.label}"| ${t}\n`;
      } else {
        md += `  ${s} --> ${t}\n`;
      }
    });
    md += `\`\`\`\n\n`;
  }

  md += `## 📖 Chapter-by-Chapter Guided Walkthrough\n\n`;

  story.chapters.forEach(chap => {
    if (options.includeCollapsibleDetails) {
      md += `<details>\n<summary><b>Chapter ${chap.chapterNumber}: ${chap.title}</b></summary>\n\n`;
    } else {
      md += `### Chapter ${chap.chapterNumber}: ${chap.title}\n\n`;
    }

    md += `> **Summary:** ${chap.summary}\n\n`;
    md += `${chap.narrative}\n\n`;

    if (chap.activeNodes.length > 0) {
      md += `**Key Modules:** ${chap.activeNodes.map(n => `\`${n.split(':').pop()}\``).join(', ')}\n\n`;
    }

    chap.codeSnippets.forEach(snip => {
      md += `#### 📄 \`${snip.filePath}\` (Lines ${snip.startLine}-${snip.endLine})\n\n`;
      if (snip.annotation) {
        md += `_${snip.annotation}_\n\n`;
      }
      md += `\`\`\`${(snip.language || story.meta.primaryLanguage).toLowerCase()}\n${snip.code}\n\`\`\`\n\n`;
    });

    if (options.includeCollapsibleDetails) {
      md += `</details>\n\n`;
    }
  });

  md += `---\n*Generated by [RepoTale](https://repotale.com) — Open-source interactive codebase storytelling.*`;

  return md;
}

export function generateStandaloneHtml(story: RepoTaleStory): string {
  const jsonState = JSON.stringify(story).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');

  return `<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RepoTale — ${story.meta.repoName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600&family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Inter', sans-serif; }
    pre, code { font-family: 'Fira Code', monospace; }
    .active-card { border-color: #6366f1 !important; box-shadow: 0 0 30px rgba(99, 102, 241, 0.25); transform: translateY(-2px); }
  </style>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen selection:bg-indigo-500 selection:text-white">
  <!-- Top Navigation Header -->
  <header class="border-b border-slate-800/80 bg-slate-900/90 backdrop-blur sticky top-0 z-50 px-6 py-3.5 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <div class="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center text-white font-bold shadow-lg shadow-indigo-500/30">
        🧭
      </div>
      <div>
        <h1 class="font-bold text-base text-white flex items-center gap-2">
          ${story.meta.repoName}
          <span class="text-xs px-2 py-0.5 rounded-full bg-indigo-950 text-indigo-300 border border-indigo-700/50">${story.meta.primaryLanguage}</span>
        </h1>
        <p class="text-xs text-slate-400 truncate max-w-md">${story.meta.description || 'Interactive Architecture Tour'}</p>
      </div>
    </div>
    <div class="flex items-center gap-3">
      <a href="https://repotale.com" target="_blank" class="text-xs font-semibold px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-all shadow-md shadow-indigo-600/20 flex items-center gap-1.5">
        <span>RepoTale Studio</span>
        <span>↗</span>
      </a>
    </div>
  </header>

  <!-- Split Screen Viewer -->
  <main class="grid grid-cols-1 lg:grid-cols-12 min-h-[calc(100vh-65px)]">
    <!-- Left Narrative Pane -->
    <div id="narrative-pane" class="lg:col-span-6 p-6 lg:p-10 space-y-10 overflow-y-auto max-h-[calc(100vh-65px)] border-r border-slate-800/80">
      <div class="p-6 rounded-2xl bg-gradient-to-br from-indigo-950/40 via-slate-900 to-slate-950 border border-indigo-500/20 shadow-xl">
        <h2 class="text-2xl font-extrabold text-white mb-2 tracking-tight">Interactive Architectural Story</h2>
        <p class="text-sm text-slate-300 leading-relaxed">${story.meta.description || 'Explore the system lifecycle and call graph below.'}</p>
        <div class="mt-4 flex flex-wrap gap-2 text-xs">
          <span class="px-2.5 py-1 rounded-md bg-slate-800 text-slate-300 font-mono">Entry: ${story.meta.entryPoint}</span>
          ${(story.meta.frameworks || []).map(f => `<span class="px-2.5 py-1 rounded-md bg-indigo-900/50 text-indigo-300 font-medium">${f}</span>`).join('')}
        </div>
      </div>

      <!-- Chapters Feed -->
      <div id="chapters-list" class="space-y-8"></div>
    </div>

    <!-- Right Dynamic Graph Canvas -->
    <div class="lg:col-span-6 sticky top-[65px] h-[calc(100vh-65px)] bg-slate-900/40 p-6 flex flex-col justify-between overflow-hidden">
      <div class="flex items-center justify-between pb-3 border-b border-slate-800/80">
        <div class="flex items-center gap-2">
          <span class="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
          <h2 class="text-xs font-bold tracking-wider uppercase text-slate-300">Live Architecture Graph</h2>
        </div>
        <span id="current-chapter-indicator" class="text-xs font-mono text-indigo-400">Chapter 1 Focus</span>
      </div>

      <!-- Mermaid Flow Container -->
      <div class="flex-1 flex items-center justify-center p-4 overflow-auto">
        <div id="mermaid-diagram" class="mermaid w-full"></div>
      </div>

      <!-- Active Focus Footer -->
      <div class="p-3.5 bg-slate-900/90 rounded-xl border border-slate-800 shadow-lg flex items-center justify-between text-xs">
        <div class="flex items-center gap-2 text-slate-300">
          <span class="font-semibold text-white">Active Nodes:</span>
          <span id="active-nodes-list" class="font-mono text-indigo-300">Loading...</span>
        </div>
        <span class="text-slate-500 text-[11px]">Scroll to change focus</span>
      </div>
    </div>
  </main>

  <script>
    const STORY = ${jsonState};

    mermaid.initialize({
      startOnLoad: false,
      theme: 'dark',
      themeVariables: {
        darkMode: true,
        primaryColor: '#6366f1',
        primaryTextColor: '#f8fafc',
        primaryBorderColor: '#4f46e5',
        lineColor: '#818cf8',
        secondaryColor: '#1e293b',
        tertiaryColor: '#0f172a'
      }
    });

    function escapeHtml(text) {
      return (text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    // Build Mermaid
    function renderDiagram() {
      let code = 'flowchart TD\\n';
      (STORY.callGraph.nodes || []).forEach(n => {
        const id = n.id.replace(/[:/.-]/g, '_');
        const label = n.label.replace(/"/g, "'");
        code += '  ' + id + '["' + label + '"]\\n';
      });
      (STORY.callGraph.edges || []).forEach(e => {
        const s = e.source.replace(/[:/.-]/g, '_');
        const t = e.target.replace(/[:/.-]/g, '_');
        if (e.label) {
          code += '  ' + s + ' -->|"' + e.label + '"| ' + t + '\\n';
        } else {
          code += '  ' + s + ' --> ' + t + '\\n';
        }
      });
      const container = document.getElementById('mermaid-diagram');
      container.innerHTML = code;
      mermaid.run({ nodes: [container] });
    }

    // Render Chapters
    const chaptersList = document.getElementById('chapters-list');
    (STORY.chapters || []).forEach((chap, i) => {
      const card = document.createElement('div');
      card.className = 'chapter-card border border-slate-800/80 bg-slate-900/60 backdrop-blur rounded-2xl p-6 transition-all duration-300 hover:border-slate-700';
      card.setAttribute('data-index', i);

      let snippets = '';
      (chap.codeSnippets || []).forEach(s => {
        snippets += \`
          <div class="mt-4 rounded-xl bg-slate-950 border border-slate-800/90 overflow-hidden shadow-inner">
            <div class="px-4 py-2 bg-slate-900/90 border-b border-slate-800 text-xs font-mono text-slate-400 flex items-center justify-between">
              <span>📄 \${escapeHtml(s.filePath)}:\${s.startLine}-\${s.endLine}</span>
              <span class="text-indigo-400 font-sans">\${escapeHtml(s.annotation || '')}</span>
            </div>
            <pre class="p-4 text-xs font-mono text-indigo-100 overflow-x-auto leading-relaxed"><code>\${escapeHtml(s.code)}</code></pre>
          </div>
        \`;
      });

      card.innerHTML = \`
        <div class="flex items-center gap-3 mb-3">
          <span class="px-2.5 py-0.5 text-xs font-bold rounded-md bg-indigo-600/20 text-indigo-400 border border-indigo-500/30">Chapter \${chap.chapterNumber}</span>
          <h3 class="text-lg font-bold text-white tracking-tight">\${escapeHtml(chap.title)}</h3>
        </div>
        <p class="text-sm font-medium text-slate-300 mb-3">\${escapeHtml(chap.summary)}</p>
        <p class="text-sm text-slate-400 leading-relaxed mb-4">\${escapeHtml(chap.narrative)}</p>
        <div class="flex flex-wrap gap-1.5 mb-2">
          \${(chap.activeNodes || []).map(nodeId => \`<span class="px-2 py-0.5 rounded text-[11px] font-mono bg-slate-800/80 text-indigo-300 border border-slate-700">\${escapeHtml(nodeId.split(':').pop())}</span>\`).join('')}
        </div>
        \${snippets}
      \`;
      chaptersList.appendChild(card);
    });

    // Parallax scroll spy
    const pane = document.getElementById('narrative-pane');
    const cards = document.querySelectorAll('.chapter-card');
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          cards.forEach(c => c.classList.remove('active-card'));
          entry.target.classList.add('active-card');
          const idx = parseInt(entry.target.getAttribute('data-index'));
          const activeChap = STORY.chapters[idx];
          if (activeChap) {
            document.getElementById('current-chapter-indicator').innerText = 'Chapter ' + activeChap.chapterNumber + ' Focus';
            document.getElementById('active-nodes-list').innerText = (activeChap.activeNodes || []).map(n => n.split(':').pop()).join(', ') || 'Global';
          }
        }
      });
    }, { root: pane, threshold: 0.5 });

    cards.forEach(c => observer.observe(c));
    if (cards[0]) cards[0].classList.add('active-card');
    renderDiagram();
  </script>
</body>
</html>`;
}
