import { RepoTaleStory } from '../types/story';
import { ExportOptions } from '../types/api';

export function generateMarkdownReadme(story: RepoTaleStory, options: ExportOptions): string {
  const user = options.githubUsername || 'username';
  const repo = options.repositoryName || story.meta.repoName.split('/').pop() || 'repo';

  let md = '';

  if (options.includeBadge) {
    md += `[![RepoTale Interactive Guide](https://img.shields.io/badge/RepoTale-Interactive_Tour-blue?style=for-the-badge&logo=compass)](https://${user}.github.io/${repo}/)\n\n`;
  }

  md += `# 🗺️ RepoTale Interactive Architecture: ${story.meta.repoName}\n\n`;
  md += `> ${story.meta.description || 'Interactive codebase walkthrough and architectural call graph.'}\n\n`;

  md += `**Primary Language:** \`${story.meta.primaryLanguage}\`  \n`;
  if (story.meta.frameworks && story.meta.frameworks.length > 0) {
    md += `**Frameworks & Libraries:** ${story.meta.frameworks.map(f => `\`${f}\``).join(', ')}  \n`;
  }
  md += `**Entrypoint:** \`${story.meta.entryPoint}\`\n\n`;

  if (options.includeMermaid) {
    md += `## 📊 System Call Graph\n\n\`\`\`mermaid\nflowchart TD\n`;
    story.callGraph.nodes.forEach(node => {
      const safeId = node.id.replace(/[:/.-]/g, '_');
      const label = node.label.replace(/"/g, "'");
      let icon = '🔧';
      if (node.type === 'entry') icon = '🚀';
      else if (node.type === 'middleware') icon = '🛡️';
      else if (node.type === 'service') icon = '⚙️';
      else if (node.type === 'data') icon = '💾';

      md += `  ${safeId}["${icon} ${label} (${node.type})"]\n`;
    });

    story.callGraph.edges.forEach(edge => {
      const s = edge.source.replace(/[:/.-]/g, '_');
      const t = edge.target.replace(/[:/.-]/g, '_');
      if (edge.label) {
        md += `  ${s} -->|"${edge.label}"| ${t}\n`;
      } else {
        md += `  ${s} --> ${t}\n`;
      }
    });
    md += `\`\`\`\n\n`;
  }

  md += `## 📖 Chapter-by-Chapter Guided Walkthrough\n\n`;

  story.chapters.forEach(chap => {
    if (options.includeCollapsibleDetails) {
      md += `<details>\n<summary><b>Chapter ${chap.chapterNumber}: ${chap.title}</b></summary>\n\n`;
    } else {
      md += `### Chapter ${chap.chapterNumber}: ${chap.title}\n\n`;
    }

    md += `> **Summary:** ${chap.summary}\n\n`;
    md += `${chap.narrative}\n\n`;

    if (chap.activeNodes.length > 0) {
      md += `**Key Modules:** ${chap.activeNodes.map(n => `\`${n.split(':').pop()}\``).join(', ')}\n\n`;
    }

    chap.codeSnippets.forEach(snip => {
      md += `#### 📄 \`${snip.filePath}\` (Lines ${snip.startLine}-${snip.endLine})\n\n`;
      if (snip.annotation) {
        md += `_${snip.annotation}_\n\n`;
      }
      md += `\`\`\`${(snip.language || story.meta.primaryLanguage).toLowerCase()}\n${snip.code}\n\`\`\`\n\n`;
    });

    if (options.includeCollapsibleDetails) {
      md += `</details>\n\n`;
    }
  });

  md += `---\n*Generated by [RepoTale](https://repotale.com) — Open-source interactive codebase storytelling.*`;

  return md;
}

export function generateStandaloneHtml(
  story: RepoTaleStory,
  sampleStories?: Record<string, RepoTaleStory>
): string {
  const allStories: Record<string, RepoTaleStory> = {
    repotale: story,
    ...(sampleStories || {})
  };
  const jsonState = JSON.stringify(story).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');
  const jsonAllStories = JSON.stringify(allStories).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');
  const githubUrl = story.meta.githubUrl || 'https://github.com/buzzcobain/RepoTale';
  const isRepoTale = story.meta.repoName === 'buzzcobain/RepoTale' || !story.meta.repoName;
  const pageTitle = isRepoTale ? 'RepoTale' : `RepoTale — ${story.meta.repoName}`;
  const canonicalUrl = isRepoTale ? 'https://repotale.com/' : (story.meta.githubUrl || 'https://repotale.com/');
  const metaDescription = `${story.meta.repoName}: ${story.meta.description || 'Interactive codebase walkthrough and visual architecture tour'}. Explore the AST call graph, key entry points, and step-by-step developer guide powered by RepoTale.`;
  const keywords = `RepoTale, ${story.meta.repoName}, codebase visualizer, software architecture, interactive code walkthrough, call graph visualizer, AST analyzer, code documentation, developer onboarding, ${story.meta.primaryLanguage}, ${(story.meta.frameworks || []).join(', ')}`;

  const escapeXml = (unsafe: string) =>
    (unsafe || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');

  const renderedChaptersByStory: Record<string, string> = {};
  for (const [key, st] of Object.entries(allStories)) {
    renderedChaptersByStory[key] = (st.chapters || []).map((chap, i) => {
      let snippets = '';
      (chap.codeSnippets || []).forEach((s, sIdx) => {
        const fileName = s.filePath.split('/').pop() || s.filePath;
        snippets += `
          <div id="snippet-${key}-${i}-${sIdx}" class="mt-4 rounded-lg bg-[#07090e] border border-slate-800 overflow-hidden transition-all duration-200">
            <div class="px-3.5 py-2 bg-slate-900/80 border-b border-slate-800 text-xs font-mono text-slate-300 flex items-center justify-between">
              <div class="flex items-center gap-3 truncate min-w-0">
                <div class="flex items-center gap-1.5 shrink-0 opacity-75">
                  <span class="w-2.5 h-2.5 rounded-full bg-[#ef4444]"></span>
                  <span class="w-2.5 h-2.5 rounded-full bg-[#eab308]"></span>
                  <span class="w-2.5 h-2.5 rounded-full bg-[#22c55e]"></span>
                </div>
                <span class="font-semibold text-slate-200 truncate">${escapeXml(fileName)}</span>
                <span class="text-slate-500 font-normal truncate hidden sm:inline">(${escapeXml(s.filePath)}) • L${s.startLine}-${s.endLine}</span>
              </div>
              <div class="flex items-center gap-2 shrink-0">
                ${s.annotation ? `<span class="badge badge-xs badge-ghost text-slate-400 font-sans hidden sm:inline">${escapeXml(s.annotation)}</span>` : ''}
                <button class="btn btn-ghost btn-xs h-6 min-h-0 px-2 font-mono text-[11px] text-slate-400 hover:text-white border border-slate-700" onclick="navigator.clipboard.writeText(this.getAttribute('data-code')).then(() => { this.innerText = 'Copied!'; setTimeout(() => this.innerText = 'Copy', 1500); })" data-code="${escapeXml(s.code)}">Copy</button>
              </div>
            </div>
            <pre class="p-4 text-xs font-mono text-slate-200 bg-[#07090e] overflow-x-auto leading-relaxed"><code>${escapeXml(s.code)}</code></pre>
          </div>
        `;
      });

      return `
        <div id="chapter-card-${i}" class="chapter-card border border-slate-800 bg-slate-900/70 rounded-xl p-6 transition-all duration-200 hover:border-slate-700" data-index="${i}">
          <div class="flex items-center gap-3 mb-2.5">
            <span class="badge badge-sm badge-neutral font-mono font-semibold text-slate-300 border border-slate-700">Chapter ${chap.chapterNumber}</span>
            <h3 class="text-base font-bold text-white tracking-tight">${escapeXml(chap.title)}</h3>
          </div>
          <div class="mb-3.5 p-3 rounded-md bg-slate-950/60 border border-slate-800/80 text-xs font-mono text-slate-300">
            <span class="text-slate-500 font-bold mr-1.5 uppercase text-[10px] tracking-wider">Summary:</span>
            ${escapeXml(chap.summary)}
          </div>
          <p class="text-xs text-slate-400 leading-relaxed mb-4">${escapeXml(chap.narrative)}</p>
          <div class="flex flex-wrap gap-1.5 mb-2">
            ${(chap.activeNodes || []).map(nodeId => `
              <span class="badge badge-xs badge-outline badge-primary font-mono cursor-pointer hover:bg-primary/20 transition-colors py-2" onclick="focusNode('${escapeXml(nodeId)}')">
                ${escapeXml(nodeId.split(':').pop() || nodeId)}
              </span>
            `).join('')}
          </div>
          ${snippets}
        </div>
      `;
    }).join('\n');
  }

  const preRenderedChapters = renderedChaptersByStory['repotale'] || renderedChaptersByStory[Object.keys(renderedChaptersByStory)[0]] || '';
  const jsonChaptersHtmlByStory = JSON.stringify(renderedChaptersByStory).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');

  return `<!DOCTYPE html>
<html lang="en" class="dark" data-theme="dim">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Primary SEO Meta Tags -->
  <title>${escapeXml(pageTitle)}</title>
  <meta name="title" content="${escapeXml(pageTitle)}">
  <meta name="description" content="${escapeXml(metaDescription)}">
  <meta name="keywords" content="${escapeXml(keywords)}">
  <meta name="author" content="RepoTale">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
  <link rel="canonical" href="${escapeXml(canonicalUrl)}">

  <!-- Favicon & Brand -->
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="shortcut icon" href="/favicon.ico">
  <meta name="theme-color" content="#090b10">
  <meta name="color-scheme" content="dark">

  <!-- Open Graph / Facebook / LinkedIn / Discord -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="${escapeXml(canonicalUrl)}">
  <meta property="og:site_name" content="RepoTale">
  <meta property="og:title" content="${escapeXml(pageTitle)}">
  <meta property="og:description" content="${escapeXml(metaDescription)}">
  <meta property="og:locale" content="en_US">

  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="${escapeXml(canonicalUrl)}">
  <meta name="twitter:title" content="${escapeXml(pageTitle)}">
  <meta name="twitter:description" content="${escapeXml(metaDescription)}">

  <!-- JSON-LD Structured Data -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "SoftwareApplication",
        "name": "RepoTale",
        "url": "https://repotale.com",
        "applicationCategory": "DeveloperApplication",
        "operatingSystem": "Web, macOS, Windows, Linux",
        "description": "Interactive, local-first codebase storytelling & AST architecture visualizer.",
        "offers": {
          "@type": "Offer",
          "price": "0",
          "priceCurrency": "USD"
        }
      },
      {
        "@type": "TechArticle",
        "headline": "${escapeXml(story.meta.repoName)} Interactive Architecture Walkthrough",
        "description": "${escapeXml(metaDescription)}",
        "url": "https://repotale.com",
        "author": {
          "@type": "Organization",
          "name": "RepoTale",
          "url": "https://repotale.com"
        },
        "about": {
          "@type": "SoftwareSourceCode",
          "name": "${escapeXml(story.meta.repoName)}",
          "programmingLanguage": "${escapeXml(story.meta.primaryLanguage)}",
          "codeRepository": "${escapeXml(githubUrl)}"
        }
      }
    ]
  }
  </script>

  <script>
    // Suppress Netlify HUD / Powered by Netlify badge
    (function() {
      function neutralize() {
        var s = document.querySelector('script[data-nf-variant]');
        if (s) { s.dataset.nfVariant = ''; s.remove(); }
        var f = document.getElementById('nl-badge-frame') || document.querySelector('iframe[title*="Netlify"]');
        if (f) { f.remove(); }
      }
      neutralize();
      var obs = new MutationObserver(neutralize);
      if (document.documentElement) {
        obs.observe(document.documentElement, { childList: true, subtree: true });
      }
      window.addEventListener('DOMContentLoaded', neutralize);
      window.addEventListener('load', neutralize);
    })();
  </script>

  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.24/dist/full.min.css" rel="stylesheet" type="text/css" />
  <script src="https://cdn.jsdelivr.net/npm/dagre@0.8.5/dist/dagre.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600&family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Inter', sans-serif; }
    /* Hide Netlify Drawer, HUD, and Powered by Netlify Badge */
    #nl-badge-frame,
    iframe[title="Powered by Netlify"],
    iframe[id*="nl-badge"],
    #netlify-hud,
    netlify-drawer,
    div[id*="netlify"],
    iframe[src*="netlify"],
    [data-netlify-hud] {
      display: none !important;
      visibility: hidden !important;
      opacity: 0 !important;
      pointer-events: none !important;
      width: 0 !important;
      height: 0 !important;
      clip-path: circle(0) !important;
      transform: scale(0) !important;
      position: absolute !important;
      top: -9999px !important;
      left: -9999px !important;
    }
    .active-card {
      border-color: #3b82f6 !important;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.4);
    }
    .dot-grid {
      background-color: #090b10;
      background-image: radial-gradient(circle, #272a34 1px, transparent 1px);
      background-size: 24px 24px;
    }
    .node-card {
      transition: border-color 0.2s ease, box-shadow 0.2s ease, opacity 0.2s ease, transform 0.2s ease;
    }
    .node-card.active-node {
      opacity: 1 !important;
      border-color: #3b82f6 !important;
      box-shadow: 0 4px 12px -2px rgba(0, 0, 0, 0.5) !important;
      transform: scale(1.01);
      z-index: 30 !important;
    }
    .node-card.inactive-node {
      opacity: 0.65;
    }
    .node-card.inactive-node:hover {
      opacity: 1;
      transform: scale(1.01);
      z-index: 25;
    }
    .edge-line {
      fill: none;
      stroke: #272a34;
      stroke-width: 1.5;
      transition: stroke 0.2s ease, stroke-width 0.2s ease;
    }
    .edge-line.active-edge {
      stroke: #3b82f6;
      stroke-width: 2;
      stroke-dasharray: 4 3;
      animation: edgeFlow 1.5s linear infinite;
    }
    @keyframes edgeFlow {
      from { stroke-dashoffset: 14; }
      to { stroke-dashoffset: 0; }
    }
  </style>
</head>
<body class="bg-base-100 text-slate-100 min-h-screen selection:bg-primary/30 selection:text-white">
  <!-- Header -->
  <header class="border-b border-base-300 bg-base-200/90 backdrop-blur sticky top-0 z-50 px-6 py-3 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <div class="w-8 h-8 rounded-lg overflow-hidden border border-base-300 bg-base-100 shrink-0">
        <svg viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-full h-full">
          <defs>
            <linearGradient id="rt-hdr-p" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stop-color="#38bdf8" />
              <stop offset="55%" stop-color="#3b82f6" />
              <stop offset="100%" stop-color="#1d4ed8" />
            </linearGradient>
            <linearGradient id="rt-hdr-b" x1="0%" y1="100%" x2="100%" y2="0%">
              <stop offset="0%" stop-color="#10b981" />
              <stop offset="100%" stop-color="#38bdf8" />
            </linearGradient>
          </defs>
          <rect width="512" height="512" rx="112" fill="#090b10" />
          <rect width="504" height="504" x="4" y="4" rx="108" stroke="#272a34" stroke-width="4" opacity="0.6" />
          <g transform="translate(0, 10)">
            <path d="M 180 370 L 180 165 C 180 140 215 130 256 148 L 256 385 C 215 368 180 370 180 370 Z" fill="url(#rt-hdr-p)" opacity="0.95" />
            <path d="M 332 370 L 332 165 C 332 140 297 130 256 148 L 256 385 C 297 368 332 370 332 370 Z" fill="url(#rt-hdr-p)" opacity="0.75" />
            <path d="M 180 350 C 180 260 210 210 295 200" stroke="url(#rt-hdr-b)" stroke-width="26" stroke-linecap="round" />
            <line x1="180" y1="160" x2="180" y2="360" stroke="#ffffff" stroke-width="24" stroke-linecap="round" />
            <circle cx="180" cy="355" r="22" fill="#090b10" stroke="#ffffff" stroke-width="12" />
            <circle cx="180" cy="165" r="22" fill="#090b10" stroke="#ffffff" stroke-width="12" />
            <circle cx="310" cy="200" r="26" fill="url(#rt-hdr-b)" stroke="#090b10" stroke-width="8" />
          </g>
        </svg>
      </div>
      <div>
        <div class="flex items-center gap-2">
          <span class="font-bold text-sm text-white tracking-tight">RepoTale</span>
          <span class="badge badge-xs badge-neutral font-mono text-[10px]">v1.0</span>
          <span class="text-slate-600 hidden sm:inline">/</span>
          <h2 class="font-medium text-xs text-slate-300 hidden sm:flex items-center gap-1.5 font-mono">
            ${story.meta.repoName}
            <span class="badge badge-xs badge-outline badge-primary font-mono">${story.meta.primaryLanguage}</span>
          </h2>
        </div>
        <p class="text-xs text-slate-400 truncate max-w-md">Interactive codebase storytelling & AST architecture visualizer</p>
      </div>
    </div>
    <div class="flex items-center gap-2">
      <a href="${githubUrl}" target="_blank" rel="noopener noreferrer" class="btn btn-neutral btn-sm normal-case font-medium border border-base-300 text-slate-300 hover:text-white flex items-center gap-2">
        <svg class="w-3.5 h-3.5 fill-current text-slate-400" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.53 1.032 1.53 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/>
        </svg>
        <span>GitHub</span>
        <span class="text-xs text-amber-400">★</span>
      </a>
    </div>
  </header>

  <!-- Split Screen Viewer -->
  <main class="grid grid-cols-1 lg:grid-cols-12 min-h-[calc(100vh-65px)] bg-base-100">
    <!-- Left Narrative Pane -->
    <div id="narrative-pane" class="lg:col-span-6 p-6 lg:p-10 space-y-10 overflow-y-auto max-h-[calc(100vh-65px)] border-r border-base-300 scroll-smooth">
      <!-- RepoTale Hero Section & Introduction -->
      <section class="p-6 lg:p-7 rounded-xl bg-base-200 border border-base-300 shadow-sm relative overflow-hidden">
        <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-6">
          <div class="flex-1">
            <div class="badge badge-sm badge-neutral gap-1.5 font-mono text-[11px] text-slate-300 mb-3 border border-base-300">
              <span class="text-primary">✨</span>
              <span>Open-Source Codebase Storytelling</span>
            </div>

            <h1 class="text-2xl lg:text-3xl font-bold text-white tracking-tight leading-tight">
              Turn complex codebases into <span class="text-primary font-extrabold">interactive visual stories</span>.
            </h1>

            <p class="mt-3 text-sm text-slate-400 leading-relaxed max-w-2xl">
              RepoTale extracts the AST call graph of any repository and generates an interactive, chapter-driven walkthrough synchronized with a visual architectural diagram.
            </p>
          </div>

          <!-- Featured Logo Lockup -->
          <div class="hidden md:flex shrink-0 p-1.5 rounded-xl bg-base-100 border border-base-300 shadow-sm">
            <svg width="105" height="130" viewBox="0 0 512 640" fill="none" xmlns="http://www.w3.org/2000/svg" class="rounded-lg">
              <defs>
                <linearGradient id="rt-hero-p" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stop-color="#38bdf8" />
                  <stop offset="55%" stop-color="#3b82f6" />
                  <stop offset="100%" stop-color="#1d4ed8" />
                </linearGradient>
                <linearGradient id="rt-hero-b" x1="0%" y1="100%" x2="100%" y2="0%">
                  <stop offset="0%" stop-color="#10b981" />
                  <stop offset="100%" stop-color="#38bdf8" />
                </linearGradient>
              </defs>
              <rect width="512" height="640" rx="48" fill="#090b10" />
              <rect width="504" height="632" x="4" y="4" rx="44" stroke="#272a34" stroke-width="2" opacity="0.6" />
              <g transform="translate(0, -20)">
                <path d="M 180 370 L 180 165 C 180 140 215 130 256 148 L 256 385 C 215 368 180 370 180 370 Z" fill="url(#rt-hero-p)" opacity="0.95" />
                <path d="M 332 370 L 332 165 C 332 140 297 130 256 148 L 256 385 C 297 368 332 370 332 370 Z" fill="url(#rt-hero-p)" opacity="0.75" />
                <path d="M 180 350 C 180 260 210 210 295 200" stroke="url(#rt-hdr-b)" stroke-width="26" stroke-linecap="round" />
                <line x1="180" y1="160" x2="180" y2="360" stroke="#ffffff" stroke-width="24" stroke-linecap="round" />
                <circle cx="180" cy="355" r="22" fill="#090b10" stroke="#ffffff" stroke-width="12" />
                <circle cx="180" cy="165" r="22" fill="#090b10" stroke="#ffffff" stroke-width="12" />
                <circle cx="310" cy="200" r="26" fill="url(#rt-hero-b)" stroke="#090b10" stroke-width="8" />
              </g>
              <text x="256" y="490" text-anchor="middle" font-family="system-ui, -apple-system, sans-serif" font-size="62" letter-spacing="-1.5">
                <tspan fill="#f8fafc" font-weight="800">Repo</tspan>
                <tspan fill="#3b82f6" font-weight="700">Tale</tspan>
              </text>
              <text x="256" y="535" text-anchor="middle" font-family="system-ui, -apple-system, monospace" font-size="16" font-weight="600" letter-spacing="5" fill="#64748b">CODEBASE STORIES</text>
            </svg>
          </div>
        </div>

        <!-- 3-Step Lifecycle: How It Works on Any Repo -->
        <div class="mt-6 mb-6">
          <div class="flex items-center gap-2 mb-3">
            <span class="badge badge-xs badge-outline badge-primary font-mono font-semibold uppercase tracking-wider">
              How It Works
            </span>
            <span class="text-xs text-slate-400">From code to hosted interactive tour in 3 steps:</span>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div class="p-3.5 rounded-lg bg-base-100 border border-base-300 shadow-none">
              <div class="text-[10px] font-mono font-semibold text-primary mb-1 flex items-center gap-1.5">
                <span>01. INGEST</span>
              </div>
              <h3 class="text-xs font-semibold text-slate-200 mb-1">Point to Any Codebase</h3>
              <p class="text-[11px] text-slate-400 leading-relaxed">
                Provide a GitHub URL or local repository folder. Tree-sitter extracts functions, call-sites, and imports across TS, Python, Rust, and Go.
              </p>
            </div>

            <div class="p-3.5 rounded-lg bg-base-100 border border-base-300 shadow-none">
              <div class="text-[10px] font-mono font-semibold text-primary mb-1 flex items-center gap-1.5">
                <span>02. VISUALIZE</span>
              </div>
              <h3 class="text-xs font-semibold text-slate-200 mb-1">Auto-Generate Story</h3>
              <p class="text-[11px] text-slate-400 leading-relaxed">
                Generates an interactive chapter-by-chapter guided walkthrough synchronized with an animated React Flow call graph.
              </p>
            </div>

            <div class="p-3.5 rounded-lg bg-base-100 border border-base-300 shadow-none">
              <div class="text-[10px] font-mono font-semibold text-primary mb-1 flex items-center gap-1.5">
                <span>03. PUBLISH</span>
              </div>
              <h3 class="text-xs font-semibold text-slate-200 mb-1">Host Free Anywhere</h3>
              <p class="text-[11px] text-slate-400 leading-relaxed">
                Emits a zero-dependency <code class="px-1 py-0.5 rounded bg-base-200 text-slate-300 font-mono text-[10px]">/docs/index.html</code>. Host 100% free on GitHub Pages, Netlify, Cloudflare, or your custom domain.
              </p>
            </div>
          </div>
        </div>

        <!-- Dual-Layer Connection Showcase -->
        <div class="p-4 rounded-lg bg-base-100 border border-base-300 mb-6">
          <div class="flex items-center justify-between mb-2">
            <span class="text-xs font-semibold text-slate-200 flex items-center gap-1.5">
              <span>🔗</span>
              <span>The Dual-Layer Connection: README to Hosted Web Tour</span>
            </span>
            <span class="badge badge-xs badge-success font-mono font-medium">
              1-Click Navigation
            </span>
          </div>
          <p class="text-xs text-slate-400 mb-3 leading-relaxed">
            RepoTale adds an interactive badge to your repository's <code class="text-slate-300 font-mono">README.md</code>. When anyone clicks it, it launches your hosted visual walkthrough on <strong>GitHub Pages</strong>, <strong>Netlify</strong>, or your own <strong>custom domain</strong>:
          </p>
          <div class="flex flex-col sm:flex-row items-center gap-3 p-3 rounded-md bg-base-200/80 border border-base-300 text-xs font-mono">
            <div class="flex items-center gap-2 shrink-0">
              <span class="text-slate-400 font-sans text-[11px]">README.md badge:</span>
              <span class="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-primary text-primary-content font-bold text-[11px]">
                🧭 RepoTale | Interactive Tour
              </span>
            </div>
            <span class="text-slate-500 hidden sm:inline shrink-0">➔</span>
            <div class="flex items-center gap-1.5 text-slate-300 truncate">
              <span class="text-slate-400 font-sans text-[11px]">Opens web tour:</span>
              <span class="underline decoration-slate-600 underline-offset-2 truncate">
                https://yourname.github.io/your-repo/
              </span>
            </div>
          </div>
        </div>

        <!-- Contributors Showcase -->
        <div class="p-3.5 rounded-lg bg-base-100 border border-base-300 mb-6 flex flex-wrap items-center justify-between gap-3">
          <div class="flex items-center gap-2.5">
            <div class="w-7 h-7 rounded-md bg-base-200 border border-base-300 flex items-center justify-center text-primary shrink-0">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
              </svg>
            </div>
            <div>
              <div class="flex items-center gap-2">
                <span class="text-xs font-semibold text-slate-200">Contributors</span>
                <span class="badge badge-xs badge-neutral font-mono text-[10px] text-slate-400">Open Source</span>
              </div>
              <p class="text-[11px] text-slate-400">Community developers building and expanding RepoTale</p>
            </div>
          </div>

          <div class="flex items-center gap-2.5">
            <div id="contributors-avatars" class="avatar-group -space-x-2.5 rtl:space-x-reverse">
              <a href="https://github.com/buzzcobain" target="_blank" rel="noopener noreferrer" class="avatar tooltip tooltip-top border-none" data-tip="@buzzcobain">
                <div class="w-7 h-7 rounded-full border border-base-300 bg-base-200 hover:scale-110 transition-transform">
                  <img src="https://github.com/buzzcobain.png" alt="buzzcobain" loading="lazy" />
                </div>
              </a>
              <a href="https://github.com/bernalalexis-try" target="_blank" rel="noopener noreferrer" class="avatar tooltip tooltip-top border-none" data-tip="@bernalalexis-try">
                <div class="w-7 h-7 rounded-full border border-base-300 bg-base-200 hover:scale-110 transition-transform">
                  <img src="https://github.com/bernalalexis-try.png" alt="bernalalexis-try" loading="lazy" />
                </div>
              </a>
            </div>

            <a href="https://github.com/buzzcobain/RepoTale/graphs/contributors" target="_blank" rel="noopener noreferrer" class="btn btn-ghost btn-xs font-mono text-[11px] text-slate-400 hover:text-white border border-base-300 gap-1">
              <span>View All</span>
              <span class="text-[10px]">↗</span>
            </a>
          </div>
        </div>

        <!-- Action Buttons & Live Demo Switcher -->
        <div class="pt-4 border-t border-base-300 flex flex-col gap-3">
          <div class="flex flex-wrap items-center justify-between gap-3">
            <div class="flex items-center gap-2 text-xs">
              <span class="w-2 h-2 rounded-full bg-emerald-400"></span>
              <span class="font-semibold text-slate-200">Live Demo:</span>
              <span id="live-demo-label" class="text-slate-400">${isRepoTale ? 'RepoTale analyzing its own architecture' : escapeXml(story.meta.repoName)}</span>
            </div>

            <div class="flex items-center gap-2">
              <a
                href="https://github.com/buzzcobain/RepoTale#quickstart"
                target="_blank"
                rel="noopener noreferrer"
                class="btn btn-primary btn-sm normal-case font-medium gap-1.5"
              >
                <span>🚀</span>
                <span>Use on Your Repo (Free)</span>
              </a>

              <a
                href="${githubUrl}"
                target="_blank"
                rel="noopener noreferrer"
                class="btn btn-neutral btn-sm normal-case font-medium border border-base-300 gap-1.5 text-slate-300 hover:text-white"
              >
                <span>View Source</span>
                <span>↗</span>
              </a>
            </div>
          </div>

          <!-- Multi-Repo Live Switcher -->
          <div class="flex flex-wrap items-center justify-between gap-2 p-2 rounded-lg bg-base-100 border border-base-300">
            <div class="flex items-center gap-2 text-xs">
              <span class="text-[10px] font-mono font-bold uppercase tracking-wider text-slate-400">Switch Demo:</span>
              <span class="text-slate-400 hidden sm:inline text-xs">Explore how RepoTale visualizes different architectures:</span>
            </div>
            <div class="flex flex-wrap items-center gap-1">
              <button
                id="btn-sample-repotale"
                onclick="switchStory('repotale')"
                class="sample-btn btn btn-xs font-mono font-medium btn-primary"
              >
                <span>🧭</span>
                <span>RepoTale (Tauri/React)</span>
              </button>
              <button
                id="btn-sample-fastapi"
                onclick="switchStory('fastapi')"
                class="sample-btn btn btn-xs font-mono font-medium btn-ghost text-slate-400 hover:text-white"
              >
                <span>⚡</span>
                <span>FastAPI (Python)</span>
              </button>
              <button
                id="btn-sample-trpc"
                onclick="switchStory('trpc')"
                class="sample-btn btn btn-xs font-mono font-medium btn-ghost text-slate-400 hover:text-white"
              >
                <span>🔗</span>
                <span>tRPC (TypeScript)</span>
              </button>
            </div>
          </div>
        </div>
      </section>

      <!-- Architecture Overview Card -->
      <div class="p-6 rounded-xl bg-base-200 border border-base-300 shadow-sm">
        <div class="flex items-center justify-between mb-2">
          <h2 class="text-base font-bold text-white tracking-tight flex items-center gap-2">
            <span>🧭</span>
            <span id="overview-repo-name">${story.meta.repoName} Architecture Tour</span>
          </h2>
          <span id="overview-chapter-count" class="badge badge-sm badge-neutral font-mono text-slate-300 border border-base-300">
            ${(story.chapters || []).length} Chapters
          </span>
        </div>
        <p id="overview-description" class="text-xs text-slate-400 leading-relaxed">${story.meta.description || 'Explore the system architecture, call graph, and data flow below.'}</p>
        <div class="mt-4 flex flex-wrap gap-2 text-xs">
          <span id="overview-entry-point" class="badge badge-sm badge-neutral font-mono text-slate-300 border border-base-300">Entry: ${story.meta.entryPoint}</span>
          <div id="overview-frameworks" class="flex flex-wrap gap-1.5">
            ${(story.meta.frameworks || []).map(f => `<span class="badge badge-sm badge-outline badge-neutral font-mono text-slate-300">${f}</span>`).join('')}
          </div>
        </div>
      </div>

      <!-- Pre-rendered Chapters List (Instant Crawler & User Rendering) -->
      <div id="chapters-list" class="space-y-8">
        ${preRenderedChapters}
      </div>

      <!-- SEO & Open Source Backlink Footer -->
      <footer class="pt-8 pb-4 border-t border-slate-800/60 text-xs text-slate-400 flex flex-col sm:flex-row items-center justify-between gap-3">
        <p>
          Generated by <a href="https://repotale.com" class="text-indigo-400 hover:text-indigo-300 font-semibold underline underline-offset-2">RepoTale</a> — Open-source codebase storytelling & visual architecture visualizer.
        </p>
        <a href="${githubUrl}" target="_blank" rel="noopener noreferrer" class="text-slate-400 hover:text-slate-200 flex items-center gap-1">
          <span>GitHub</span>
          <span>↗</span>
        </a>
      </footer>
    </div>

    <!-- Right Dynamic Graph Canvas -->
    <div class="lg:col-span-6 sticky top-[65px] h-[calc(100vh-65px)] flex flex-col justify-between overflow-hidden bg-[#080a0f] relative select-none">
      <!-- Top Graph Bar -->
      <div class="px-5 py-2.5 border-b border-base-300 bg-base-200/90 backdrop-blur-md flex items-center justify-between z-20 shrink-0">
        <div class="flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-emerald-400"></span>
          <h2 class="text-xs font-mono font-bold tracking-wider uppercase text-slate-200">Interactive Architecture Graph</h2>
        </div>
        <span id="current-chapter-indicator" class="badge badge-sm badge-neutral font-mono text-slate-300 border border-base-300">
          Chapter 1 Focus
        </span>
      </div>

      <!-- Floating Controls -->
      <div class="absolute top-14 right-5 z-30 flex items-center gap-1 p-1 rounded-lg bg-base-200/90 border border-base-300 backdrop-blur-md shadow-sm text-xs">
        <button id="btn-zoom-in" title="Zoom In" class="btn btn-ghost btn-xs h-7 w-7 p-0 text-slate-400 hover:text-white font-mono text-sm">+</button>
        <button id="btn-zoom-out" title="Zoom Out" class="btn btn-ghost btn-xs h-7 w-7 p-0 text-slate-400 hover:text-white font-mono text-sm">−</button>
        <button id="btn-fit" title="Fit to Screen" class="btn btn-ghost btn-xs h-7 px-2 text-slate-400 hover:text-white font-mono text-[11px]">
          <svg class="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/></svg>
          <span>Fit</span>
        </button>
        <div class="h-3.5 w-[1px] bg-base-300 mx-0.5"></div>
        <button id="btn-dir" title="Toggle Layout Direction (TB: Top-Bottom / LR: Left-Right)" class="btn btn-ghost btn-xs h-7 px-2 text-primary font-mono text-[11px]">
          <span id="dir-label">TB</span>
        </button>
      </div>

      <!-- Interactive Canvas Viewport -->
      <div id="graph-viewport" class="flex-1 relative dot-grid overflow-hidden cursor-grab active:cursor-grabbing">
        <div id="graph-surface" class="absolute inset-0 origin-top-left will-change-transform">
          <!-- SVG Edges Layer -->
          <svg id="graph-edges-svg" class="absolute inset-0 w-full h-full pointer-events-none overflow-visible" style="min-width: 3000px; min-height: 3000px;">
            <defs>
              <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#475569" />
              </marker>
              <marker id="arrow-active" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#3b82f6" />
              </marker>
            </defs>
            <g id="edges-group"></g>
          </svg>

          <!-- HTML Nodes Layer -->
          <div id="graph-nodes-layer" class="absolute inset-0 pointer-events-auto" style="min-width: 3000px; min-height: 3000px;"></div>
        </div>

        <!-- Legend Pill (Bottom Left) -->
        <div class="absolute bottom-4 left-4 z-30 hidden sm:flex items-center gap-3 px-3 py-1.5 rounded-lg bg-base-200/90 border border-base-300 backdrop-blur-md text-[10px] text-slate-400 font-mono shadow-sm">
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-sky-400"></span><span>Entry</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-amber-400"></span><span>Middleware</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-blue-400"></span><span>Service</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-emerald-400"></span><span>Data</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-slate-400"></span><span>Utility</span></div>
        </div>

        <!-- Minimap (Bottom Right) -->
        <div id="minimap-container" class="absolute bottom-4 right-4 z-30 w-36 h-24 rounded-lg bg-base-200/90 border border-base-300 backdrop-blur-md overflow-hidden shadow-sm hidden md:block">
          <svg id="minimap-svg" class="w-full h-full"></svg>
          <div id="minimap-viewport" class="absolute border border-primary bg-primary/15 pointer-events-none rounded transition-all duration-75"></div>
        </div>
      </div>

      <!-- Active Focus Footer Bar -->
      <div class="px-4 py-2 bg-base-200/90 border-t border-base-300 shadow-sm flex items-center justify-between text-xs z-20 shrink-0 font-mono">
        <div class="flex items-center gap-2 text-slate-400 truncate mr-2 text-[11px]">
          <span class="font-semibold text-slate-200">Active Focus:</span>
          <span id="active-nodes-list" class="text-primary truncate">Loading...</span>
        </div>
        <span class="text-slate-500 text-[10px] shrink-0">Click node to jump to story</span>
      </div>
    </div>
  </main>

  <script>
    const ALL_STORIES = ${jsonAllStories};
    const CHAPTERS_HTML = ${jsonChaptersHtmlByStory};
    let currentStoryKey = 'repotale';
    let STORY = ALL_STORIES['repotale'] || ALL_STORIES[Object.keys(ALL_STORIES)[0]] || ${jsonState};

    const typeConfig = {
      entry: {
        badgeClass: 'badge-info',
        badgeText: 'Entrypoint',
        color: '#38bdf8',
        iconSvg: '<svg class="w-3 h-3 text-sky-400" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>'
      },
      middleware: {
        badgeClass: 'badge-warning',
        badgeText: 'Middleware',
        color: '#fbbf24',
        iconSvg: '<svg class="w-3 h-3 text-amber-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>'
      },
      service: {
        badgeClass: 'badge-primary',
        badgeText: 'Service',
        color: '#3b82f6',
        iconSvg: '<svg class="w-3 h-3 text-blue-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3M15 1v3M9 20v3M15 20v3M20 9h3M20 14h3M1 9h3M1 14h3"/></svg>'
      },
      data: {
        badgeClass: 'badge-success',
        badgeText: 'Data/Store',
        color: '#34d399',
        iconSvg: '<svg class="w-3 h-3 text-emerald-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>'
      },
      utility: {
        badgeClass: 'badge-neutral',
        badgeText: 'Utility',
        color: '#94a3b8',
        iconSvg: '<svg class="w-3 h-3 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>'
      }
    };

    function escapeHtml(text) {
      return (text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    let currentDirection = 'TB';
    let layoutNodes = [];
    let layoutEdges = [];
    let activeNodeIds = new Set();
    let selectedNodeId = null;

    // Viewport transform state
    const transform = { x: 40, y: 40, k: 0.85 };
    let isDragging = false;
    let dragStartX = 0;
    let dragStartY = 0;

    const viewport = document.getElementById('graph-viewport');
    const surface = document.getElementById('graph-surface');
    const edgesGroup = document.getElementById('edges-group');
    const nodesLayer = document.getElementById('graph-nodes-layer');

    function applyTransform(smooth = false) {
      if (smooth) {
        surface.style.transition = 'transform 0.4s cubic-bezier(0.16, 1, 0.3, 1)';
        setTimeout(() => { surface.style.transition = ''; }, 450);
      }
      surface.style.transform = \`translate(\${transform.x}px, \${transform.y}px) scale(\${transform.k})\`;
      updateMinimap();
    }

    // Compute Graph Layout (Dagre + Tiered Fallback)
    function computeLayout(dir = 'TB') {
      const rawNodes = STORY.callGraph.nodes || [];
      const rawEdges = STORY.callGraph.edges || [];
      const nodeWidth = 240;
      const nodeHeight = 90;

      if (typeof dagre !== 'undefined' && dagre.graphlib) {
        const g = new dagre.graphlib.Graph();
        g.setGraph({ rankdir: dir, nodesep: 50, ranksep: 75, marginx: 40, marginy: 40 });
        g.setDefaultEdgeLabel(() => ({}));
        rawNodes.forEach(n => g.setNode(n.id, { width: nodeWidth, height: nodeHeight }));
        rawEdges.forEach(e => g.setEdge(e.source, e.target));
        dagre.layout(g);

        layoutNodes = rawNodes.map(n => {
          const pos = g.node(n.id) || { x: 200, y: 200 };
          return {
            ...n,
            width: nodeWidth,
            height: nodeHeight,
            x: pos.x - nodeWidth / 2,
            y: pos.y - nodeHeight / 2,
          };
        });
      } else {
        // Fallback tiered grid layout
        const tiers = { entry: 0, middleware: 1, service: 2, data: 3, utility: 4 };
        const buckets = [[], [], [], [], []];
        rawNodes.forEach(n => {
          const t = tiers[n.type] ?? 2;
          buckets[t].push(n);
        });

        layoutNodes = [];
        buckets.forEach((bucket, tierIdx) => {
          const total = bucket.length;
          bucket.forEach((node, colIdx) => {
            const x = dir === 'TB' ? (colIdx - (total - 1) / 2) * 280 + 350 : tierIdx * 320 + 80;
            const y = dir === 'TB' ? tierIdx * 160 + 80 : (colIdx - (total - 1) / 2) * 140 + 300;
            layoutNodes.push({ ...node, x, y, width: nodeWidth, height: nodeHeight });
          });
        });
      }

      layoutEdges = rawEdges;
    }

    // Render Canvas
    function renderGraph() {
      // 1. Render Edges (Curved Bezier Paths)
      let svgHtml = '';
      layoutEdges.forEach(edge => {
        const s = layoutNodes.find(n => n.id === edge.source);
        const t = layoutNodes.find(n => n.id === edge.target);
        if (!s || !t) return;

        let sx, sy, tx, ty, c1x, c1y, c2x, c2y;
        if (currentDirection === 'TB') {
          sx = s.x + s.width / 2;
          sy = s.y + s.height;
          tx = t.x + t.width / 2;
          ty = t.y;
          const dy = Math.max(30, (ty - sy) / 2);
          c1x = sx;
          c1y = sy + dy;
          c2x = tx;
          c2y = ty - dy;
        } else {
          sx = s.x + s.width;
          sy = s.y + s.height / 2;
          tx = t.x;
          ty = t.y + t.height / 2;
          const dx = Math.max(30, (tx - sx) / 2);
          c1x = sx + dx;
          c1y = sy;
          c2x = tx - dx;
          c2y = ty;
        }

        const pathD = \`M \${sx} \${sy} C \${c1x} \${c1y}, \${c2x} \${c2y}, \${tx} \${ty}\`;
        const isActiveEdge = (activeNodeIds.has(edge.source) || Array.from(activeNodeIds).some(id => id.split(':').pop() === edge.source.split(':').pop())) &&
          (activeNodeIds.has(edge.target) || Array.from(activeNodeIds).some(id => id.split(':').pop() === edge.target.split(':').pop()));
        const edgeClass = isActiveEdge ? 'edge-line active-edge' : 'edge-line';
        const marker = isActiveEdge ? 'url(#arrow-active)' : 'url(#arrow)';

        svgHtml += \`<path d="\${pathD}" class="\${edgeClass}" marker-end="\${marker}" data-edge-source="\${escapeHtml(edge.source)}" data-edge-target="\${escapeHtml(edge.target)}" />\`;

        // Optional Edge Label Badge
        if (edge.label) {
          const mx = (sx + tx) / 2;
          const my = (sy + ty) / 2;
          svgHtml += \`
            <foreignObject x="\${mx - 60}" y="\${my - 12}" width="120" height="24" class="overflow-visible pointer-events-none">
              <div xmlns="http://www.w3.org/1999/xhtml" class="flex items-center justify-center">
                <span class="px-2 py-0.5 rounded-full bg-slate-950/95 border border-slate-700/80 text-[10px] font-mono text-slate-300 shadow-md truncate max-w-[110px]">
                  \${escapeHtml(edge.label)}
                </span>
              </div>
            </foreignObject>
          \`;
        }
      });
      edgesGroup.innerHTML = svgHtml;

      // 2. Render Nodes
      let nodesHtml = '';
      layoutNodes.forEach(node => {
        const style = typeConfig[node.type] || typeConfig.utility;
        const isActive = activeNodeIds.has(node.id);
        const isSelected = selectedNodeId === node.id;
        const cardStateClass = isSelected
          ? 'border-primary ring-1 ring-primary/60 active-node'
          : isActive
          ? 'active-node'
          : 'inactive-node';

        nodesHtml += \`
          <div
            id="node-\${CSS.escape(node.id)}"
            data-node-id="\${escapeHtml(node.id)}"
            class="node-card absolute w-[230px] rounded-lg p-3 cursor-pointer select-none border border-slate-800 bg-[#0e121a] \${cardStateClass}"
            style="left: \${node.x}px; top: \${node.y}px;"
          >
            <!-- Port Handles -->
            <div class="absolute -top-1 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full bg-slate-400 border border-slate-900"></div>
            <div class="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full bg-slate-400 border border-slate-900"></div>

            <!-- Top Row: Icon & Badge -->
            <div class="flex items-center justify-between mb-1.5">
              <div class="flex items-center gap-1.5">
                \${style.iconSvg}
                <span class="badge badge-xs badge-outline \${style.badgeClass} font-mono text-[10px]">
                  \${style.badgeText}
                </span>
              </div>
              <span class="beacon w-2 h-2 rounded-full bg-primary \${isActive ? '' : 'hidden'}" title="Active node in story"></span>
            </div>

            <!-- Title -->
            <div class="font-mono font-semibold text-xs text-white truncate mb-1">
              \${escapeHtml(node.label)}
            </div>

            <!-- File Path & Line Range -->
            <div class="flex items-center justify-between text-[10px] font-mono text-slate-400">
              <span class="truncate max-w-[125px]">
                \${escapeHtml(node.filePath.split('/').pop() || node.filePath)}
              </span>
              <span class="text-slate-500">
                \${node.lineRange ? 'L' + node.lineRange[0] + '-' + node.lineRange[1] : ''}
              </span>
            </div>

            <!-- Description -->
            \${node.description ? \`
              <p class="text-[10px] text-slate-400 line-clamp-2 leading-relaxed mt-1 border-t border-slate-800/80 pt-1">
                \${escapeHtml(node.description)}
              </p>
            \` : ''}
          </div>
        \`;
      });
      nodesLayer.innerHTML = nodesHtml;

      // Attach Node Click Listeners (jump to chapter)
      document.querySelectorAll('.node-card').forEach(card => {
        card.addEventListener('click', (e) => {
          e.stopPropagation();
          const nid = card.getAttribute('data-node-id');
          selectedNodeId = nid;
          highlightActiveNodes(activeNodeIds);

          // Find chapter
          const cards = document.querySelectorAll('.chapter-card');
          const targetIdx = STORY.chapters.findIndex(ch =>
            (ch.activeNodes || []).includes(nid) ||
            (ch.activeNodes || []).some(id => id.split(':').pop() === nid.split(':').pop())
          );

          if (targetIdx !== -1 && cards[targetIdx]) {
            cards[targetIdx].scrollIntoView({ behavior: 'smooth', block: 'start' });
            cards[targetIdx].classList.add('ring-4', 'ring-indigo-400');
            setTimeout(() => cards[targetIdx].classList.remove('ring-4', 'ring-indigo-400'), 1800);
          }
        });
      });

      updateMinimap();
    }

    // Fit View
    function fitView(smooth = true) {
      if (!layoutNodes.length) return;
      const vpWidth = viewport.clientWidth;
      const vpHeight = viewport.clientHeight;

      let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
      layoutNodes.forEach(n => {
        minX = Math.min(minX, n.x);
        maxX = Math.max(maxX, n.x + n.width);
        minY = Math.min(minY, n.y);
        maxY = Math.max(maxY, n.y + n.height);
      });

      const graphWidth = maxX - minX;
      const graphHeight = maxY - minY;
      const padding = 80;

      const scaleX = (vpWidth - padding * 2) / graphWidth;
      const scaleY = (vpHeight - padding * 2) / graphHeight;
      const scale = Math.min(1.2, Math.max(0.3, Math.min(scaleX, scaleY)));

      transform.k = scale;
      transform.x = (vpWidth - graphWidth * scale) / 2 - minX * scale;
      transform.y = (vpHeight - graphHeight * scale) / 2 - minY * scale;

      applyTransform(smooth);
    }

    // Center on specific active nodes
    function centerOnNodes(nodeIds) {
      const targets = layoutNodes.filter(n => nodeIds.has(n.id) || Array.from(nodeIds).some(nid => nid.split(':').pop() === n.id.split(':').pop()));
      if (!targets.length) return;

      const vpWidth = viewport.clientWidth;
      const vpHeight = viewport.clientHeight;

      let avgX = 0, avgY = 0;
      targets.forEach(t => {
        avgX += t.x + t.width / 2;
        avgY += t.y + t.height / 2;
      });
      avgX /= targets.length;
      avgY /= targets.length;

      transform.x = vpWidth / 2 - avgX * transform.k;
      transform.y = vpHeight / 2 - avgY * transform.k;
      applyTransform(true);
    }

    // Update active highlight
    function highlightActiveNodes(nodeIds) {
      activeNodeIds = new Set(nodeIds);
      document.querySelectorAll('.node-card').forEach(el => {
        const nid = el.getAttribute('data-node-id');
        const isActive = activeNodeIds.has(nid) || Array.from(activeNodeIds).some(id => id.split(':').pop() === nid.split(':').pop());
        const isSelected = selectedNodeId === nid;
        const beacon = el.querySelector('.beacon');

        if (isSelected) {
          el.className = el.className.replace(/inactive-node|active-node/g, '').trim() + ' active-node ring-2 ring-indigo-400 border-indigo-400';
          if (beacon) beacon.classList.remove('hidden');
        } else if (isActive) {
          el.className = el.className.replace(/inactive-node|ring-2 ring-indigo-400 border-indigo-400/g, '').trim() + ' active-node';
          if (beacon) beacon.classList.remove('hidden');
        } else {
          el.className = el.className.replace(/active-node|ring-2 ring-indigo-400 border-indigo-400/g, '').trim() + ' inactive-node';
          if (beacon) beacon.classList.add('hidden');
        }
      });

      // Update edges
      document.querySelectorAll('.edge-line').forEach(line => {
        const src = line.getAttribute('data-edge-source');
        const tgt = line.getAttribute('data-edge-target');
        const isEdgeActive = (activeNodeIds.has(src) || Array.from(activeNodeIds).some(id => id.split(':').pop() === src.split(':').pop())) &&
          (activeNodeIds.has(tgt) || Array.from(activeNodeIds).some(id => id.split(':').pop() === tgt.split(':').pop()));
        if (isEdgeActive) {
          line.classList.add('active-edge');
          line.setAttribute('marker-end', 'url(#arrow-active)');
        } else {
          line.classList.remove('active-edge');
          line.setAttribute('marker-end', 'url(#arrow)');
        }
      });
    }

    // Minimap
    function updateMinimap() {
      const miniSvg = document.getElementById('minimap-svg');
      const miniVp = document.getElementById('minimap-viewport');
      if (!miniSvg || !miniVp || !layoutNodes.length) return;

      let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
      layoutNodes.forEach(n => {
        minX = Math.min(minX, n.x);
        maxX = Math.max(maxX, n.x + n.width);
        minY = Math.min(minY, n.y);
        maxY = Math.max(maxY, n.y + n.height);
      });

      const gw = Math.max(100, maxX - minX + 160);
      const gh = Math.max(100, maxY - minY + 160);
      const mw = 144;
      const mh = 96;
      const scale = Math.min(mw / gw, mh / gh);

      let dots = '';
      layoutNodes.forEach(n => {
        const nx = (n.x - minX + 80) * scale;
        const ny = (n.y - minY + 80) * scale;
        const nw = Math.max(6, n.width * scale);
        const nh = Math.max(3, n.height * scale);
        const cfg = typeConfig[n.type] || typeConfig.utility;
        const isActive = activeNodeIds.has(n.id);
        dots += \`<rect x="\${nx}" y="\${ny}" width="\${nw}" height="\${nh}" rx="2" fill="\${cfg.color}" opacity="\${isActive ? 1 : 0.4}"/>\`;
      });
      miniSvg.innerHTML = dots;

      // Viewport box
      const vpW = viewport.clientWidth;
      const vpH = viewport.clientHeight;
      const curX = (-transform.x / transform.k - minX + 80) * scale;
      const curY = (-transform.y / transform.k - minY + 80) * scale;
      const curW = Math.max(12, (vpW / transform.k) * scale);
      const curH = Math.max(12, (vpH / transform.k) * scale);

      miniVp.style.left = Math.max(0, Math.min(mw - 10, curX)) + 'px';
      miniVp.style.top = Math.max(0, Math.min(mh - 10, curY)) + 'px';
      miniVp.style.width = Math.min(mw, curW) + 'px';
      miniVp.style.height = Math.min(mh, curH) + 'px';
    }

    // Pan & Zoom Event Listeners
    viewport.addEventListener('mousedown', (e) => {
      if (e.target.closest('.node-card')) return;
      isDragging = true;
      dragStartX = e.clientX - transform.x;
      dragStartY = e.clientY - transform.y;
    });

    window.addEventListener('mousemove', (e) => {
      if (!isDragging) return;
      transform.x = e.clientX - dragStartX;
      transform.y = e.clientY - dragStartY;
      applyTransform(false);
    });

    window.addEventListener('mouseup', () => { isDragging = false; });

    let touchStartX = 0;
    let touchStartY = 0;
    viewport.addEventListener('touchstart', (e) => {
      if (e.target.closest('.node-card')) return;
      if (e.touches.length === 1) {
        isDragging = true;
        touchStartX = e.touches[0].clientX - transform.x;
        touchStartY = e.touches[0].clientY - transform.y;
      }
    }, { passive: true });

    window.addEventListener('touchmove', (e) => {
      if (!isDragging || e.touches.length !== 1) return;
      transform.x = e.touches[0].clientX - touchStartX;
      transform.y = e.touches[0].clientY - touchStartY;
      applyTransform(false);
    }, { passive: true });

    window.addEventListener('touchend', () => { isDragging = false; });

    viewport.addEventListener('wheel', (e) => {
      e.preventDefault();
      const rect = viewport.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;
      const mouseY = e.clientY - rect.top;
      const zoomFactor = e.deltaY < 0 ? 1.1 : 0.9;
      const newK = Math.max(0.25, Math.min(2.2, transform.k * zoomFactor));

      transform.x = mouseX - (mouseX - transform.x) * (newK / transform.k);
      transform.y = mouseY - (mouseY - transform.y) * (newK / transform.k);
      transform.k = newK;
      applyTransform(false);
    }, { passive: false });

    // Floating Button Controls
    document.getElementById('btn-zoom-in').onclick = () => {
      transform.k = Math.min(2.2, transform.k * 1.2);
      applyTransform(true);
    };
    document.getElementById('btn-zoom-out').onclick = () => {
      transform.k = Math.max(0.25, transform.k * 0.8);
      applyTransform(true);
    };
    document.getElementById('btn-fit').onclick = () => fitView(true);
    document.getElementById('btn-dir').onclick = () => {
      currentDirection = currentDirection === 'TB' ? 'LR' : 'TB';
      document.getElementById('dir-label').innerText = currentDirection;
      computeLayout(currentDirection);
      renderGraph();
      fitView(true);
    };

    window.focusNode = function(nid) {
      selectedNodeId = nid;
      highlightActiveNodes(new Set([nid]));
      centerOnNodes(new Set([nid]));

      const cards = document.querySelectorAll('.chapter-card');
      for (let i = 0; i < cards.length; i++) {
        const c = cards[i];
        const idx = parseInt(c.getAttribute('data-index'));
        const chap = STORY.chapters[idx];
        if (chap && (chap.activeNodes || []).includes(nid)) {
          c.scrollIntoView({ behavior: 'smooth', block: 'start' });
          c.classList.add('ring-4', 'ring-indigo-400');
          setTimeout(() => c.classList.remove('ring-4', 'ring-indigo-400'), 1800);
          break;
        }
      }
    };

    function renderChaptersList() {
      const container = document.getElementById('chapters-list');
      if (!container) return;
      container.innerHTML = CHAPTERS_HTML[currentStoryKey] || '';
      reObserveCards();
    }

    let observer = null;
    function reObserveCards() {
      if (observer) {
        observer.disconnect();
      }
      const pane = document.getElementById('narrative-pane');
      const cards = document.querySelectorAll('.chapter-card');
      observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            cards.forEach(c => c.classList.remove('active-card'));
            entry.target.classList.add('active-card');
            const idx = parseInt(entry.target.getAttribute('data-index'));
            const activeChap = STORY.chapters[idx];
            if (activeChap) {
              selectedNodeId = null;
              document.getElementById('current-chapter-indicator').innerText = 'Chapter ' + activeChap.chapterNumber + ' Focus';
              const nodeLabels = (activeChap.activeNodes || []).map(n => n.split(':').pop()).join(', ') || 'Global';
              document.getElementById('active-nodes-list').innerText = nodeLabels;

              const activeSet = new Set(activeChap.activeNodes || []);
              highlightActiveNodes(activeSet);
              centerOnNodes(activeSet);
            }
          }
        });
      }, { root: pane, threshold: 0.45 });

      cards.forEach(c => observer.observe(c));
    }

    window.switchStory = function(key) {
      if (!ALL_STORIES[key]) return;
      currentStoryKey = key;
      STORY = ALL_STORIES[key];

      // Update sample switcher button styles
      document.querySelectorAll('.sample-btn').forEach(btn => {
        btn.className = 'sample-btn btn btn-xs font-mono font-medium btn-ghost text-slate-400 hover:text-white';
      });
      const activeBtn = document.getElementById('btn-sample-' + key);
      if (activeBtn) {
        activeBtn.className = 'sample-btn btn btn-xs font-mono font-medium btn-primary';
      }

      // Update Architecture Overview Card
      const nameEl = document.getElementById('overview-repo-name');
      if (nameEl) nameEl.innerText = (STORY.meta.repoName || 'Codebase') + ' Architecture Tour';
      const countEl = document.getElementById('overview-chapter-count');
      if (countEl) countEl.innerText = (STORY.chapters || []).length + ' Chapters';
      const descEl = document.getElementById('overview-description');
      if (descEl) descEl.innerText = STORY.meta.description || 'Explore the system architecture, call graph, and data flow below.';
      const entryEl = document.getElementById('overview-entry-point');
      if (entryEl) entryEl.innerText = 'Entry: ' + (STORY.meta.entryPoint || 'unknown');
      const fwEl = document.getElementById('overview-frameworks');
      if (fwEl) {
        fwEl.innerHTML = (STORY.meta.frameworks || []).map(f => '<span class="badge badge-sm badge-outline badge-neutral font-mono text-slate-300">' + escapeHtml(f) + '</span>').join('');
      }
      const demoLabel = document.getElementById('live-demo-label');
      if (demoLabel) {
        demoLabel.innerText = key === 'repotale' ? 'RepoTale analyzing its own architecture' : (STORY.meta.repoName + ' architecture');
      }

      selectedNodeId = null;
      renderChaptersList();
      computeLayout(currentDirection);
      renderGraph();
      fitView(true);

      const pane = document.getElementById('narrative-pane');
      if (pane) {
        pane.scrollTo({ top: 0, behavior: 'smooth' });
      }

      setTimeout(() => {
        const firstCard = document.querySelector('.chapter-card');
        if (firstCard) {
          firstCard.classList.add('active-card');
          const firstChap = STORY.chapters[0];
          if (firstChap) {
            const firstSet = new Set(firstChap.activeNodes || []);
            highlightActiveNodes(firstSet);
            centerOnNodes(firstSet);
          }
        }
      }, 100);
    };

    // Initialize Layout, Graph & Scroll Spy
    computeLayout('TB');
    renderGraph();
    reObserveCards();

    setTimeout(() => {
      fitView(false);
      const firstCard = document.querySelector('.chapter-card');
      if (firstCard) {
        firstCard.classList.add('active-card');
        const firstChap = STORY.chapters[0];
        if (firstChap) {
          const firstSet = new Set(firstChap.activeNodes || []);
          highlightActiveNodes(firstSet);
          centerOnNodes(firstSet);
        }
      }
    }, 100);

    // Fetch live contributors for avatars
    try {
      fetch('https://api.github.com/repos/buzzcobain/RepoTale/contributors')
        .then(function(res) { return res.ok ? res.json() : []; })
        .then(function(data) {
          if (!Array.isArray(data) || data.length === 0) return;
          var group = document.getElementById('contributors-avatars');
          if (!group) return;
          var existing = {};
          var links = group.querySelectorAll('a');
          for (var i = 0; i < links.length; i++) {
            var href = links[i].getAttribute('href') || '';
            var login = href.split('/').pop();
            if (login) existing[login] = true;
          }
          data.forEach(function(c) {
            if (!existing[c.login] && c.avatar_url) {
              var a = document.createElement('a');
              a.href = c.html_url || ('https://github.com/' + c.login);
              a.target = '_blank';
              a.rel = 'noopener noreferrer';
              a.className = 'avatar tooltip tooltip-top border-none';
              a.setAttribute('data-tip', '@' + c.login);
              a.innerHTML = '<div class="w-7 h-7 rounded-full border border-base-300 bg-base-200 hover:scale-110 transition-transform"><img src="' + c.avatar_url + '" alt="' + c.login + '" loading="lazy" /></div>';
              group.appendChild(a);
            }
          });
        })
        .catch(function() {});
    } catch (e) {}
  </script>
</body>
</html>`;
}
