import { RepoTaleStory } from '../types/story';
import { ExportOptions } from '../types/api';

export function generateMarkdownReadme(story: RepoTaleStory, options: ExportOptions): string {
  const user = options.githubUsername || 'username';
  const repo = options.repositoryName || story.meta.repoName.split('/').pop() || 'repo';

  let md = '';

  if (options.includeBadge) {
    md += `[![RepoTale Interactive Guide](https://img.shields.io/badge/RepoTale-Interactive_Tour-blue?style=for-the-badge&logo=compass)](https://${user}.github.io/${repo}/)\n\n`;
  }

  md += `# 🗺️ RepoTale Interactive Architecture: ${story.meta.repoName}\n\n`;
  md += `> ${story.meta.description || 'Interactive codebase walkthrough and architectural call graph.'}\n\n`;

  md += `**Primary Language:** \`${story.meta.primaryLanguage}\`  \n`;
  if (story.meta.frameworks && story.meta.frameworks.length > 0) {
    md += `**Frameworks & Libraries:** ${story.meta.frameworks.map(f => `\`${f}\``).join(', ')}  \n`;
  }
  md += `**Entrypoint:** \`${story.meta.entryPoint}\`\n\n`;

  if (options.includeMermaid) {
    md += `## 📊 System Call Graph\n\n\`\`\`mermaid\nflowchart TD\n`;
    story.callGraph.nodes.forEach(node => {
      const safeId = node.id.replace(/[:/.-]/g, '_');
      const label = node.label.replace(/"/g, "'");
      let icon = '🔧';
      if (node.type === 'entry') icon = '🚀';
      else if (node.type === 'middleware') icon = '🛡️';
      else if (node.type === 'service') icon = '⚙️';
      else if (node.type === 'data') icon = '💾';

      md += `  ${safeId}["${icon} ${label} (${node.type})"]\n`;
    });

    story.callGraph.edges.forEach(edge => {
      const s = edge.source.replace(/[:/.-]/g, '_');
      const t = edge.target.replace(/[:/.-]/g, '_');
      if (edge.label) {
        md += `  ${s} -->|"${edge.label}"| ${t}\n`;
      } else {
        md += `  ${s} --> ${t}\n`;
      }
    });
    md += `\`\`\`\n\n`;
  }

  md += `## 📖 Chapter-by-Chapter Guided Walkthrough\n\n`;

  story.chapters.forEach(chap => {
    if (options.includeCollapsibleDetails) {
      md += `<details>\n<summary><b>Chapter ${chap.chapterNumber}: ${chap.title}</b></summary>\n\n`;
    } else {
      md += `### Chapter ${chap.chapterNumber}: ${chap.title}\n\n`;
    }

    md += `> **Summary:** ${chap.summary}\n\n`;
    md += `${chap.narrative}\n\n`;

    if (chap.activeNodes.length > 0) {
      md += `**Key Modules:** ${chap.activeNodes.map(n => `\`${n.split(':').pop()}\``).join(', ')}\n\n`;
    }

    chap.codeSnippets.forEach(snip => {
      md += `#### 📄 \`${snip.filePath}\` (Lines ${snip.startLine}-${snip.endLine})\n\n`;
      if (snip.annotation) {
        md += `_${snip.annotation}_\n\n`;
      }
      md += `\`\`\`${(snip.language || story.meta.primaryLanguage).toLowerCase()}\n${snip.code}\n\`\`\`\n\n`;
    });

    if (options.includeCollapsibleDetails) {
      md += `</details>\n\n`;
    }
  });

  md += `---\n*Generated by [RepoTale](https://repotale.com) — Open-source interactive codebase storytelling.*`;

  return md;
}

export function generateStandaloneHtml(story: RepoTaleStory): string {
  const jsonState = JSON.stringify(story).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');
  const githubUrl = story.meta.githubUrl || 'https://github.com/buzzcobain/RepoTale';
  const pageTitle = `${story.meta.repoName} — Architecture & Interactive Code Tour | RepoTale`;
  const metaDescription = `${story.meta.repoName}: ${story.meta.description || 'Interactive codebase walkthrough and visual architecture tour'}. Explore the AST call graph, key entry points, and step-by-step developer guide powered by RepoTale.`;
  const keywords = `RepoTale, ${story.meta.repoName}, codebase visualizer, software architecture, interactive code walkthrough, call graph visualizer, AST analyzer, code documentation, developer onboarding, ${story.meta.primaryLanguage}, ${(story.meta.frameworks || []).join(', ')}`;

  const escapeXml = (unsafe: string) =>
    (unsafe || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');

  const preRenderedChapters = (story.chapters || []).map((chap, i) => {
    let snippets = '';
    (chap.codeSnippets || []).forEach((s, sIdx) => {
      snippets += `
        <div id="snippet-${i}-${sIdx}" class="mt-4 rounded-xl bg-slate-950 border border-slate-800/90 overflow-hidden shadow-inner transition-all duration-300">
          <div class="px-4 py-2 bg-slate-900/90 border-b border-slate-800 text-xs font-mono text-slate-400 flex items-center justify-between">
            <div class="flex items-center gap-2 truncate">
              <span>📄</span>
              <span class="truncate">${escapeXml(s.filePath)}:${s.startLine}-${s.endLine}</span>
            </div>
            <div class="flex items-center gap-3 shrink-0">
              <span class="text-indigo-400 font-sans font-medium hidden sm:inline">${escapeXml(s.annotation || '')}</span>
              <button class="px-2 py-0.5 text-[11px] rounded bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors" onclick="navigator.clipboard.writeText(this.getAttribute('data-code')).then(() => { this.innerText = 'Copied!'; setTimeout(() => this.innerText = 'Copy', 1500); })" data-code="${escapeXml(s.code)}">Copy</button>
            </div>
          </div>
          <pre class="p-4 text-xs font-mono text-indigo-100 overflow-x-auto leading-relaxed"><code>${escapeXml(s.code)}</code></pre>
        </div>
      `;
    });

    return `
      <div id="chapter-card-${i}" class="chapter-card border border-slate-800/80 bg-slate-900/60 backdrop-blur rounded-2xl p-6 transition-all duration-300 hover:border-slate-700" data-index="${i}">
        <div class="flex items-center gap-3 mb-3">
          <span class="px-2.5 py-0.5 text-xs font-bold rounded-md bg-indigo-600/20 text-indigo-400 border border-indigo-500/30 font-mono">Chapter ${chap.chapterNumber}</span>
          <h3 class="text-lg font-bold text-white tracking-tight">${escapeXml(chap.title)}</h3>
        </div>
        <p class="text-sm font-medium text-slate-300 mb-3">${escapeXml(chap.summary)}</p>
        <p class="text-sm text-slate-400 leading-relaxed mb-4">${escapeXml(chap.narrative)}</p>
        <div class="flex flex-wrap gap-1.5 mb-2">
          ${(chap.activeNodes || []).map(nodeId => `
            <span class="px-2 py-0.5 rounded text-[11px] font-mono bg-slate-800/80 text-indigo-300 border border-slate-700 hover:border-indigo-500 cursor-pointer transition-colors" onclick="focusNode('${escapeXml(nodeId)}')">
              ${escapeXml(nodeId.split(':').pop() || nodeId)}
            </span>
          `).join('')}
        </div>
        ${snippets}
      </div>
    `;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Primary SEO Meta Tags -->
  <title>${escapeXml(pageTitle)}</title>
  <meta name="title" content="${escapeXml(pageTitle)}">
  <meta name="description" content="${escapeXml(metaDescription)}">
  <meta name="keywords" content="${escapeXml(keywords)}">
  <meta name="author" content="RepoTale">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
  <link rel="canonical" href="https://repotale.com/">

  <!-- Favicon & Brand -->
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg width='512' height='512' viewBox='0 0 512 512' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3ClinearGradient id='p' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%2338bdf8'/%3E%3Cstop offset='55%25' stop-color='%236366f1'/%3E%3Cstop offset='100%25' stop-color='%23a855f7'/%3E%3C/linearGradient%3E%3ClinearGradient id='b' x1='0%25' y1='100%25' x2='100%25' y2='0%25'%3E%3Cstop offset='0%25' stop-color='%2334d399'/%3E%3Cstop offset='100%25' stop-color='%2338bdf8'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='512' height='512' rx='112' fill='%230f172a'/%3E%3Crect width='504' height='504' x='4' y='4' rx='108' stroke='%23334155' stroke-width='4' opacity='0.5'/%3E%3Cg transform='translate(0, 10)'%3E%3Cpath d='M 180 370 L 180 165 C 180 140 215 130 256 148 L 256 385 C 215 368 180 370 180 370 Z' fill='url(%23p)' opacity='0.95'/%3E%3Cpath d='M 332 370 L 332 165 C 332 140 297 130 256 148 L 256 385 C 297 368 332 370 332 370 Z' fill='url(%23p)' opacity='0.75'/%3E%3Cpath d='M 180 350 C 180 260 210 210 295 200' stroke='url(%23b)' stroke-width='26' stroke-linecap='round'/%3E%3Cline x1='180' y1='160' x2='180' y2='360' stroke='%23ffffff' stroke-width='24' stroke-linecap='round'/%3E%3Ccircle cx='180' cy='355' r='22' fill='%230f172a' stroke='%23ffffff' stroke-width='12'/%3E%3Ccircle cx='180' cy='165' r='22' fill='%230f172a' stroke='%23ffffff' stroke-width='12'/%3E%3Ccircle cx='310' cy='200' r='26' fill='url(%23b)' stroke='%230f172a' stroke-width='8'/%3E%3C/g%3E%3C/svg%3E">
  <meta name="theme-color" content="#020617">
  <meta name="color-scheme" content="dark">

  <!-- Open Graph / Facebook / LinkedIn / Discord -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://repotale.com/">
  <meta property="og:site_name" content="RepoTale">
  <meta property="og:title" content="${escapeXml(pageTitle)}">
  <meta property="og:description" content="${escapeXml(metaDescription)}">
  <meta property="og:locale" content="en_US">

  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="https://repotale.com/">
  <meta name="twitter:title" content="${escapeXml(pageTitle)}">
  <meta name="twitter:description" content="${escapeXml(metaDescription)}">

  <!-- JSON-LD Structured Data -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "SoftwareApplication",
        "name": "RepoTale",
        "url": "https://repotale.com",
        "applicationCategory": "DeveloperApplication",
        "operatingSystem": "Web, macOS, Windows, Linux",
        "description": "Interactive, local-first codebase storytelling & AST architecture visualizer.",
        "offers": {
          "@type": "Offer",
          "price": "0",
          "priceCurrency": "USD"
        }
      },
      {
        "@type": "TechArticle",
        "headline": "${escapeXml(story.meta.repoName)} Interactive Architecture Walkthrough",
        "description": "${escapeXml(metaDescription)}",
        "url": "https://repotale.com",
        "author": {
          "@type": "Organization",
          "name": "RepoTale",
          "url": "https://repotale.com"
        },
        "about": {
          "@type": "SoftwareSourceCode",
          "name": "${escapeXml(story.meta.repoName)}",
          "programmingLanguage": "${escapeXml(story.meta.primaryLanguage)}",
          "codeRepository": "${escapeXml(githubUrl)}"
        }
      }
    ]
  }
  </script>

  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/dagre@0.8.5/dist/dagre.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600&family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Inter', sans-serif; }
    /* Hide Netlify Drawer / HUD badge */
    #netlify-hud,
    netlify-drawer,
    div[id*="netlify"],
    iframe[src*="netlify"],
    [data-netlify-hud] {
      display: none !important;
      visibility: hidden !important;
      opacity: 0 !important;
      pointer-events: none !important;
    }
    .active-card {
      border-color: #6366f1 !important;
      box-shadow: 0 0 35px rgba(99, 102, 241, 0.35);
      transform: translateY(-2px);
    }
    .dot-grid {
      background-color: #030712;
      background-image: radial-gradient(circle, #334155 1.5px, transparent 1.5px);
      background-size: 24px 24px;
    }
    .node-card {
      transition: border-color 0.3s ease, box-shadow 0.3s ease, opacity 0.3s ease, transform 0.25s ease;
    }
    .node-card.active-node {
      opacity: 1 !important;
      border-color: #818cf8 !important;
      box-shadow: 0 0 30px rgba(99, 102, 241, 0.45), 0 12px 24px -6px rgba(0, 0, 0, 0.6) !important;
      transform: scale(1.03);
      z-index: 30 !important;
    }
    .node-card.inactive-node {
      opacity: 0.55;
    }
    .node-card.inactive-node:hover {
      opacity: 1;
      transform: scale(1.02);
      z-index: 25;
    }
    .edge-line {
      fill: none;
      stroke: #475569;
      stroke-width: 2;
      transition: stroke 0.3s ease, stroke-width 0.3s ease, filter 0.3s ease;
    }
    .edge-line.active-edge {
      stroke: #818cf8;
      stroke-width: 2.5;
      filter: drop-shadow(0 0 6px rgba(129, 140, 248, 0.7));
      stroke-dasharray: 6 4;
      animation: edgeFlow 1.2s linear infinite;
    }
    @keyframes edgeFlow {
      from { stroke-dashoffset: 20; }
      to { stroke-dashoffset: 0; }
    }
  </style>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen selection:bg-indigo-500 selection:text-white">
  <!-- Header -->
  <header class="border-b border-slate-800/80 bg-slate-900/90 backdrop-blur sticky top-0 z-50 px-6 py-3.5 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <div class="w-9 h-9 rounded-xl overflow-hidden shadow-lg shadow-indigo-500/25 shrink-0">
        <svg viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-full h-full">
          <defs>
            <linearGradient id="rt-hdr-p" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stop-color="#38bdf8" />
              <stop offset="55%" stop-color="#6366f1" />
              <stop offset="100%" stop-color="#a855f7" />
            </linearGradient>
            <linearGradient id="rt-hdr-b" x1="0%" y1="100%" x2="100%" y2="0%">
              <stop offset="0%" stop-color="#34d399" />
              <stop offset="100%" stop-color="#38bdf8" />
            </linearGradient>
          </defs>
          <rect width="512" height="512" rx="112" fill="#0f172a" />
          <rect width="504" height="504" x="4" y="4" rx="108" stroke="#334155" stroke-width="4" opacity="0.5" />
          <g transform="translate(0, 10)">
            <path d="M 180 370 L 180 165 C 180 140 215 130 256 148 L 256 385 C 215 368 180 370 180 370 Z" fill="url(#rt-hdr-p)" opacity="0.95" />
            <path d="M 332 370 L 332 165 C 332 140 297 130 256 148 L 256 385 C 297 368 332 370 332 370 Z" fill="url(#rt-hdr-p)" opacity="0.75" />
            <path d="M 180 350 C 180 260 210 210 295 200" stroke="url(#rt-hdr-b)" stroke-width="26" stroke-linecap="round" />
            <line x1="180" y1="160" x2="180" y2="360" stroke="#ffffff" stroke-width="24" stroke-linecap="round" />
            <circle cx="180" cy="355" r="22" fill="#0f172a" stroke="#ffffff" stroke-width="12" />
            <circle cx="180" cy="165" r="22" fill="#0f172a" stroke="#ffffff" stroke-width="12" />
            <circle cx="310" cy="200" r="26" fill="url(#rt-hdr-b)" stroke="#0f172a" stroke-width="8" />
          </g>
        </svg>
      </div>
      <div>
        <div class="flex items-center gap-2">
          <span class="font-extrabold text-sm text-white tracking-tight">RepoTale</span>
          <span class="text-[10px] px-1.5 py-0.5 rounded bg-indigo-500/20 text-indigo-300 font-semibold border border-indigo-500/30">v1.0</span>
          <span class="text-slate-600 hidden sm:inline">/</span>
          <h2 class="font-medium text-xs text-slate-300 hidden sm:flex items-center gap-1.5 font-mono">
            ${story.meta.repoName}
            <span class="text-[10px] px-1.5 py-0.2 rounded bg-slate-800 text-slate-400 border border-slate-700 font-mono">${story.meta.primaryLanguage}</span>
          </h2>
        </div>
        <p class="text-xs text-slate-400 truncate max-w-md">Interactive codebase storytelling & AST architecture visualizer</p>
      </div>
    </div>
    <div class="flex items-center gap-3">
      <a href="${githubUrl}" target="_blank" rel="noopener noreferrer" class="text-xs font-semibold px-3.5 py-1.5 rounded-lg bg-slate-800/90 hover:bg-slate-700 text-slate-200 hover:text-white border border-slate-700 hover:border-slate-600 transition-all shadow-sm flex items-center gap-2 group">
        <svg class="w-4 h-4 fill-current text-slate-400 group-hover:text-white transition-colors" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.53 1.032 1.53 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/>
        </svg>
        <span>GitHub</span>
        <span class="text-xs text-amber-400">★</span>
      </a>
    </div>
  </header>

  <!-- Split Screen Viewer -->
  <main class="grid grid-cols-1 lg:grid-cols-12 min-h-[calc(100vh-65px)]">
    <!-- Left Narrative Pane -->
    <div id="narrative-pane" class="lg:col-span-6 p-6 lg:p-10 space-y-10 overflow-y-auto max-h-[calc(100vh-65px)] border-r border-slate-800/80 scroll-smooth">
      <!-- RepoTale Hero Section & Introduction -->
      <section class="p-6 lg:p-8 rounded-2xl bg-gradient-to-br from-indigo-950/60 via-slate-900 to-slate-950 border border-indigo-500/30 shadow-2xl relative overflow-hidden">
        <div class="absolute -top-16 -right-16 w-56 h-56 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none"></div>

        <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-6">
          <div class="flex-1">
            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/15 border border-indigo-400/30 text-indigo-300 text-[11px] font-medium mb-3">
              <span>✨</span>
              <span>Open-Source Codebase Storytelling</span>
            </div>

            <h1 class="text-2xl lg:text-3xl font-black text-white tracking-tight leading-tight">
              Turn complex codebases into <span class="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-300 to-pink-400">interactive visual stories</span>.
            </h1>

            <p class="mt-3 text-sm text-slate-300 leading-relaxed">
              RepoTale solves the cognitive overload of onboarding into unfamiliar repositories. It ingests your project, extracts the AST call graph, and generates an interactive, chapter-driven walkthrough synchronized with a visual architectural diagram.
            </p>
          </div>

          <!-- Featured Logo Lockup -->
          <div class="hidden md:flex shrink-0 p-1.5 rounded-2xl bg-slate-900/80 border border-slate-800/90 shadow-2xl">
            <svg width="115" height="144" viewBox="0 0 512 640" fill="none" xmlns="http://www.w3.org/2000/svg" class="rounded-xl">
              <defs>
                <linearGradient id="rt-hero-p" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stop-color="#38bdf8" />
                  <stop offset="55%" stop-color="#6366f1" />
                  <stop offset="100%" stop-color="#a855f7" />
                </linearGradient>
                <linearGradient id="rt-hero-b" x1="0%" y1="100%" x2="100%" y2="0%">
                  <stop offset="0%" stop-color="#34d399" />
                  <stop offset="100%" stop-color="#38bdf8" />
                </linearGradient>
              </defs>
              <rect width="512" height="640" rx="48" fill="#0f172a" />
              <rect width="504" height="632" x="4" y="4" rx="44" stroke="#334155" stroke-width="2" opacity="0.5" />
              <g transform="translate(0, -20)">
                <path d="M 180 370 L 180 165 C 180 140 215 130 256 148 L 256 385 C 215 368 180 370 180 370 Z" fill="url(#rt-hero-p)" opacity="0.95" />
                <path d="M 332 370 L 332 165 C 332 140 297 130 256 148 L 256 385 C 297 368 332 370 332 370 Z" fill="url(#rt-hero-p)" opacity="0.75" />
                <path d="M 180 350 C 180 260 210 210 295 200" stroke="url(#rt-hero-b)" stroke-width="26" stroke-linecap="round" />
                <line x1="180" y1="160" x2="180" y2="360" stroke="#ffffff" stroke-width="24" stroke-linecap="round" />
                <circle cx="180" cy="355" r="22" fill="#0f172a" stroke="#ffffff" stroke-width="12" />
                <circle cx="180" cy="165" r="22" fill="#0f172a" stroke="#ffffff" stroke-width="12" />
                <circle cx="310" cy="200" r="26" fill="url(#rt-hero-b)" stroke="#0f172a" stroke-width="8" />
              </g>
              <text x="256" y="490" text-anchor="middle" font-family="system-ui, -apple-system, sans-serif" font-size="62" letter-spacing="-1.5">
                <tspan fill="#f8fafc" font-weight="800">Repo</tspan>
                <tspan fill="url(#rt-hero-p)" font-weight="700">Tale</tspan>
              </text>
              <text x="256" y="535" text-anchor="middle" font-family="system-ui, -apple-system, monospace" font-size="16" font-weight="600" letter-spacing="5" fill="#94a3b8">CODEBASE STORIES</text>
            </svg>
          </div>
        </div>

        <!-- 3 Feature Pillars -->
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-6">
          <div class="p-3.5 rounded-xl bg-slate-900/80 border border-slate-800/90 shadow-sm">
            <div class="text-lg mb-1.5">🗺️</div>
            <h2 class="text-xs font-bold text-slate-200">Interactive Call Graph</h2>
            <p class="text-[11px] text-slate-400 mt-1 leading-normal">Dynamic visual canvas tracking entrypoints, classes, and service dependencies.</p>
          </div>
          <div class="p-3.5 rounded-xl bg-slate-900/80 border border-slate-800/90 shadow-sm">
            <div class="text-lg mb-1.5">📜</div>
            <h2 class="text-xs font-bold text-slate-200">Parallax Narrative</h2>
            <p class="text-[11px] text-slate-400 mt-1 leading-normal">Scroll chapters as the camera choreographs to highlight active subgraphs.</p>
          </div>
          <div class="p-3.5 rounded-xl bg-slate-900/80 border border-slate-800/90 shadow-sm">
            <div class="text-lg mb-1.5">🔒</div>
            <h2 class="text-xs font-bold text-slate-200">100% Local-First</h2>
            <p class="text-[11px] text-slate-400 mt-1 leading-normal">Tree-sitter AST parsing with sandboxed git clones and optional Ollama support.</p>
          </div>
        </div>

        <!-- Live Demo Notice & Action Buttons -->
        <div class="mt-6 pt-5 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3">
          <div class="flex items-center gap-2 text-xs text-indigo-300">
            <span class="relative flex h-2 w-2">
              <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span class="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            <span class="font-medium text-emerald-300">Live Demo Below:</span>
            <span class="text-slate-300">RepoTale exploring its own codebase</span>
          </div>

          <div class="flex items-center gap-2.5">
            <a href="${githubUrl}" target="_blank" rel="noopener noreferrer" class="px-3.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold transition-all shadow-md shadow-indigo-600/25 flex items-center gap-1.5">
              <span>View on GitHub</span>
              <span>↗</span>
            </a>
          </div>
        </div>
      </section>

      <!-- Architecture Overview Card -->
      <div class="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 shadow-lg">
        <div class="flex items-center justify-between mb-2">
          <h2 class="text-lg font-bold text-white tracking-tight flex items-center gap-2">
            <span>🧭</span>
            <span>${story.meta.repoName} Architecture Tour</span>
          </h2>
          <span class="text-xs font-mono text-indigo-400 bg-indigo-950/60 px-2.5 py-0.5 rounded border border-indigo-800/40">
            ${(story.chapters || []).length} Chapters
          </span>
        </div>
        <p class="text-sm text-slate-300 leading-relaxed">${story.meta.description || 'Explore the system architecture, call graph, and data flow below.'}</p>
        <div class="mt-4 flex flex-wrap gap-2 text-xs">
          <span class="px-2.5 py-1 rounded-md bg-slate-800 text-slate-300 font-mono">Entry: ${story.meta.entryPoint}</span>
          ${(story.meta.frameworks || []).map(f => `<span class="px-2.5 py-1 rounded-md bg-indigo-900/50 text-indigo-300 font-medium">${f}</span>`).join('')}
        </div>
      </div>

      <!-- Pre-rendered Chapters List (Instant Crawler & User Rendering) -->
      <div id="chapters-list" class="space-y-8">
        ${preRenderedChapters}
      </div>

      <!-- SEO & Open Source Backlink Footer -->
      <footer class="pt-8 pb-4 border-t border-slate-800/60 text-xs text-slate-400 flex flex-col sm:flex-row items-center justify-between gap-3">
        <p>
          Generated by <a href="https://repotale.com" class="text-indigo-400 hover:text-indigo-300 font-semibold underline underline-offset-2">RepoTale</a> — Open-source codebase storytelling & visual architecture visualizer.
        </p>
        <a href="${githubUrl}" target="_blank" rel="noopener noreferrer" class="text-slate-400 hover:text-slate-200 flex items-center gap-1">
          <span>GitHub</span>
          <span>↗</span>
        </a>
      </footer>
    </div>

    <!-- Right Dynamic Graph Canvas -->
    <div class="lg:col-span-6 sticky top-[65px] h-[calc(100vh-65px)] flex flex-col justify-between overflow-hidden bg-slate-950 relative select-none">
      <!-- Top Graph Bar -->
      <div class="px-5 py-3 border-b border-slate-800/80 bg-slate-900/80 backdrop-blur-md flex items-center justify-between z-20 shrink-0">
        <div class="flex items-center gap-2">
          <span class="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse"></span>
          <h2 class="text-xs font-bold tracking-wider uppercase text-slate-200">Interactive Architecture Graph</h2>
        </div>
        <span id="current-chapter-indicator" class="text-xs font-mono text-indigo-400 bg-indigo-950/60 px-2.5 py-1 rounded-md border border-indigo-800/50">
          Chapter 1 Focus
        </span>
      </div>

      <!-- Floating Controls -->
      <div class="absolute top-16 right-5 z-30 flex items-center gap-1.5 p-1 rounded-xl bg-slate-900/90 border border-slate-800 backdrop-blur-md shadow-2xl text-xs">
        <button id="btn-zoom-in" title="Zoom In" class="w-7 h-7 rounded-lg hover:bg-slate-800 text-slate-200 flex items-center justify-center font-bold text-base transition-colors">+</button>
        <button id="btn-zoom-out" title="Zoom Out" class="w-7 h-7 rounded-lg hover:bg-slate-800 text-slate-200 flex items-center justify-center font-bold text-base transition-colors">−</button>
        <button id="btn-fit" title="Fit to Screen" class="px-2.5 h-7 rounded-lg hover:bg-slate-800 text-slate-200 flex items-center gap-1 font-mono text-[11px] transition-colors">
          <svg class="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/></svg>
          <span>Fit</span>
        </button>
        <div class="h-4 w-[1px] bg-slate-800 mx-0.5"></div>
        <button id="btn-dir" title="Toggle Layout Direction (TB: Top-Bottom / LR: Left-Right)" class="px-2.5 h-7 rounded-lg hover:bg-slate-800 text-indigo-300 font-mono text-[11px] flex items-center gap-1 transition-colors">
          <span id="dir-label">TB</span>
        </button>
      </div>

      <!-- Interactive Canvas Viewport -->
      <div id="graph-viewport" class="flex-1 relative dot-grid overflow-hidden cursor-grab active:cursor-grabbing">
        <div id="graph-surface" class="absolute inset-0 origin-top-left will-change-transform">
          <!-- SVG Edges Layer -->
          <svg id="graph-edges-svg" class="absolute inset-0 w-full h-full pointer-events-none overflow-visible" style="min-width: 3000px; min-height: 3000px;">
            <defs>
              <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#64748b" />
              </marker>
              <marker id="arrow-active" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#818cf8" />
              </marker>
            </defs>
            <g id="edges-group"></g>
          </svg>

          <!-- HTML Nodes Layer -->
          <div id="graph-nodes-layer" class="absolute inset-0 pointer-events-auto" style="min-width: 3000px; min-height: 3000px;"></div>
        </div>

        <!-- Legend Pill (Bottom Left) -->
        <div class="absolute bottom-4 left-4 z-30 hidden sm:flex items-center gap-3 px-3 py-2 rounded-xl bg-slate-900/90 border border-slate-800 backdrop-blur-md text-[10px] text-slate-300 font-medium shadow-lg">
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-sky-400"></span><span>Entry</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-amber-400"></span><span>Middleware</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-indigo-400"></span><span>Service</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-emerald-400"></span><span>Data</span></div>
          <div class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-slate-400"></span><span>Utility</span></div>
        </div>

        <!-- Minimap (Bottom Right) -->
        <div id="minimap-container" class="absolute bottom-4 right-4 z-30 w-36 h-24 rounded-xl bg-slate-950/90 border border-slate-800 backdrop-blur-md overflow-hidden shadow-2xl hidden md:block">
          <svg id="minimap-svg" class="w-full h-full"></svg>
          <div id="minimap-viewport" class="absolute border border-indigo-400 bg-indigo-500/15 pointer-events-none rounded transition-all duration-75"></div>
        </div>
      </div>

      <!-- Active Focus Footer Bar -->
      <div class="p-3.5 bg-slate-900/90 border-t border-slate-800 shadow-lg flex items-center justify-between text-xs z-20 shrink-0">
        <div class="flex items-center gap-2 text-slate-300 truncate mr-2">
          <span class="font-semibold text-white">Active Focus:</span>
          <span id="active-nodes-list" class="font-mono text-indigo-300 truncate">Loading...</span>
        </div>
        <span class="text-slate-500 text-[11px] shrink-0">Click any node to jump to story</span>
      </div>
    </div>
  </main>

  <script>
    const STORY = ${jsonState};

    const typeConfig = {
      entry: {
        bg: 'bg-sky-950/70',
        border: 'border-sky-500/40',
        badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/30',
        badgeText: 'Entrypoint',
        color: '#38bdf8',
        iconSvg: '<svg class="w-3.5 h-3.5 text-sky-400" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>'
      },
      middleware: {
        bg: 'bg-amber-950/70',
        border: 'border-amber-500/40',
        badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
        badgeText: 'Middleware',
        color: '#fbbf24',
        iconSvg: '<svg class="w-3.5 h-3.5 text-amber-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>'
      },
      service: {
        bg: 'bg-indigo-950/70',
        border: 'border-indigo-500/40',
        badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
        badgeText: 'Service',
        color: '#818cf8',
        iconSvg: '<svg class="w-3.5 h-3.5 text-indigo-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3M15 1v3M9 20v3M15 20v3M20 9h3M20 14h3M1 9h3M1 14h3"/></svg>'
      },
      data: {
        bg: 'bg-emerald-950/70',
        border: 'border-emerald-500/40',
        badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
        badgeText: 'Data/Store',
        color: '#34d399',
        iconSvg: '<svg class="w-3.5 h-3.5 text-emerald-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>'
      },
      utility: {
        bg: 'bg-slate-900/80',
        border: 'border-slate-700/60',
        badgeBg: 'bg-slate-800 text-slate-300 border-slate-700',
        badgeText: 'Utility',
        color: '#94a3b8',
        iconSvg: '<svg class="w-3.5 h-3.5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>'
      }
    };

    function escapeHtml(text) {
      return (text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    let currentDirection = 'TB';
    let layoutNodes = [];
    let layoutEdges = [];
    let activeNodeIds = new Set();
    let selectedNodeId = null;

    // Viewport transform state
    const transform = { x: 40, y: 40, k: 0.85 };
    let isDragging = false;
    let dragStartX = 0;
    let dragStartY = 0;

    const viewport = document.getElementById('graph-viewport');
    const surface = document.getElementById('graph-surface');
    const edgesGroup = document.getElementById('edges-group');
    const nodesLayer = document.getElementById('graph-nodes-layer');

    function applyTransform(smooth = false) {
      if (smooth) {
        surface.style.transition = 'transform 0.4s cubic-bezier(0.16, 1, 0.3, 1)';
        setTimeout(() => { surface.style.transition = ''; }, 450);
      }
      surface.style.transform = \`translate(\${transform.x}px, \${transform.y}px) scale(\${transform.k})\`;
      updateMinimap();
    }

    // Compute Graph Layout (Dagre + Tiered Fallback)
    function computeLayout(dir = 'TB') {
      const rawNodes = STORY.callGraph.nodes || [];
      const rawEdges = STORY.callGraph.edges || [];
      const nodeWidth = 240;
      const nodeHeight = 90;

      if (typeof dagre !== 'undefined' && dagre.graphlib) {
        const g = new dagre.graphlib.Graph();
        g.setGraph({ rankdir: dir, nodesep: 50, ranksep: 75, marginx: 40, marginy: 40 });
        g.setDefaultEdgeLabel(() => ({}));
        rawNodes.forEach(n => g.setNode(n.id, { width: nodeWidth, height: nodeHeight }));
        rawEdges.forEach(e => g.setEdge(e.source, e.target));
        dagre.layout(g);

        layoutNodes = rawNodes.map(n => {
          const pos = g.node(n.id) || { x: 200, y: 200 };
          return {
            ...n,
            width: nodeWidth,
            height: nodeHeight,
            x: pos.x - nodeWidth / 2,
            y: pos.y - nodeHeight / 2,
          };
        });
      } else {
        // Fallback tiered grid layout
        const tiers = { entry: 0, middleware: 1, service: 2, data: 3, utility: 4 };
        const buckets = [[], [], [], [], []];
        rawNodes.forEach(n => {
          const t = tiers[n.type] ?? 2;
          buckets[t].push(n);
        });

        layoutNodes = [];
        buckets.forEach((bucket, tierIdx) => {
          const total = bucket.length;
          bucket.forEach((node, colIdx) => {
            const x = dir === 'TB' ? (colIdx - (total - 1) / 2) * 280 + 350 : tierIdx * 320 + 80;
            const y = dir === 'TB' ? tierIdx * 160 + 80 : (colIdx - (total - 1) / 2) * 140 + 300;
            layoutNodes.push({ ...node, x, y, width: nodeWidth, height: nodeHeight });
          });
        });
      }

      layoutEdges = rawEdges;
    }

    // Render Canvas
    function renderGraph() {
      // 1. Render Edges (Curved Bezier Paths)
      let svgHtml = '';
      layoutEdges.forEach(edge => {
        const s = layoutNodes.find(n => n.id === edge.source);
        const t = layoutNodes.find(n => n.id === edge.target);
        if (!s || !t) return;

        let sx, sy, tx, ty, c1x, c1y, c2x, c2y;
        if (currentDirection === 'TB') {
          sx = s.x + s.width / 2;
          sy = s.y + s.height;
          tx = t.x + t.width / 2;
          ty = t.y;
          const dy = Math.max(30, (ty - sy) / 2);
          c1x = sx;
          c1y = sy + dy;
          c2x = tx;
          c2y = ty - dy;
        } else {
          sx = s.x + s.width;
          sy = s.y + s.height / 2;
          tx = t.x;
          ty = t.y + t.height / 2;
          const dx = Math.max(30, (tx - sx) / 2);
          c1x = sx + dx;
          c1y = sy;
          c2x = tx - dx;
          c2y = ty;
        }

        const pathD = \`M \${sx} \${sy} C \${c1x} \${c1y}, \${c2x} \${c2y}, \${tx} \${ty}\`;
        const isActiveEdge = (activeNodeIds.has(edge.source) || Array.from(activeNodeIds).some(id => id.split(':').pop() === edge.source.split(':').pop())) &&
          (activeNodeIds.has(edge.target) || Array.from(activeNodeIds).some(id => id.split(':').pop() === edge.target.split(':').pop()));
        const edgeClass = isActiveEdge ? 'edge-line active-edge' : 'edge-line';
        const marker = isActiveEdge ? 'url(#arrow-active)' : 'url(#arrow)';

        svgHtml += \`<path d="\${pathD}" class="\${edgeClass}" marker-end="\${marker}" data-edge-source="\${escapeHtml(edge.source)}" data-edge-target="\${escapeHtml(edge.target)}" />\`;

        // Optional Edge Label Badge
        if (edge.label) {
          const mx = (sx + tx) / 2;
          const my = (sy + ty) / 2;
          svgHtml += \`
            <foreignObject x="\${mx - 60}" y="\${my - 12}" width="120" height="24" class="overflow-visible pointer-events-none">
              <div xmlns="http://www.w3.org/1999/xhtml" class="flex items-center justify-center">
                <span class="px-2 py-0.5 rounded-full bg-slate-950/95 border border-slate-700/80 text-[10px] font-mono text-slate-300 shadow-md truncate max-w-[110px]">
                  \${escapeHtml(edge.label)}
                </span>
              </div>
            </foreignObject>
          \`;
        }
      });
      edgesGroup.innerHTML = svgHtml;

      // 2. Render Nodes
      let nodesHtml = '';
      layoutNodes.forEach(node => {
        const style = typeConfig[node.type] || typeConfig.utility;
        const isActive = activeNodeIds.has(node.id);
        const isSelected = selectedNodeId === node.id;
        const cardStateClass = isSelected
          ? 'ring-2 ring-indigo-400 border-indigo-400 scale-[1.03] active-node'
          : isActive
          ? 'active-node'
          : 'inactive-node';

        nodesHtml += \`
          <div
            id="node-\${CSS.escape(node.id)}"
            data-node-id="\${escapeHtml(node.id)}"
            class="node-card absolute w-[240px] rounded-xl p-3.5 backdrop-blur-md cursor-pointer select-none shadow-xl border \${style.bg} \${style.border} \${cardStateClass}"
            style="left: \${node.x}px; top: \${node.y}px;"
          >
            <!-- Port Handles -->
            <div class="absolute -top-1 left-1/2 -translate-x-1/2 w-2.5 h-2.5 rounded-full bg-indigo-400 border-2 border-slate-950"></div>
            <div class="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2.5 h-2.5 rounded-full bg-indigo-400 border-2 border-slate-950"></div>

            <!-- Top Row: Icon & Badge -->
            <div class="flex items-center justify-between mb-1.5">
              <div class="flex items-center gap-1.5">
                \${style.iconSvg}
                <span class="text-[10px] font-semibold px-2 py-0.5 rounded-full border \${style.badgeBg}">
                  \${style.badgeText}
                </span>
              </div>
              <span class="beacon flex h-2 w-2 relative \${isActive ? '' : 'hidden'}">
                <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                <span class="relative inline-flex rounded-full h-2 w-2 bg-indigo-500"></span>
              </span>
            </div>

            <!-- Title -->
            <div class="font-bold text-xs text-white tracking-tight mb-1 truncate font-mono">
              \${escapeHtml(node.label)}
            </div>

            <!-- File Path & Line Range -->
            <div class="text-[10px] font-mono text-slate-400 mb-1.5 truncate flex items-center gap-1">
              <span>📄</span>
              <span class="truncate">\${escapeHtml(node.filePath)}:\${node.lineRange ? node.lineRange[0] + '-' + node.lineRange[1] : ''}</span>
            </div>

            <!-- Description -->
            \${node.description ? \`
              <p class="text-[10px] text-slate-300/80 line-clamp-2 leading-relaxed">
                \${escapeHtml(node.description)}
              </p>
            \` : ''}
          </div>
        \`;
      });
      nodesLayer.innerHTML = nodesHtml;

      // Attach Node Click Listeners (jump to chapter)
      document.querySelectorAll('.node-card').forEach(card => {
        card.addEventListener('click', (e) => {
          e.stopPropagation();
          const nid = card.getAttribute('data-node-id');
          selectedNodeId = nid;
          highlightActiveNodes(activeNodeIds);

          // Find chapter
          const cards = document.querySelectorAll('.chapter-card');
          const targetIdx = STORY.chapters.findIndex(ch =>
            (ch.activeNodes || []).includes(nid) ||
            (ch.activeNodes || []).some(id => id.split(':').pop() === nid.split(':').pop())
          );

          if (targetIdx !== -1 && cards[targetIdx]) {
            cards[targetIdx].scrollIntoView({ behavior: 'smooth', block: 'start' });
            cards[targetIdx].classList.add('ring-4', 'ring-indigo-400');
            setTimeout(() => cards[targetIdx].classList.remove('ring-4', 'ring-indigo-400'), 1800);
          }
        });
      });

      updateMinimap();
    }

    // Fit View
    function fitView(smooth = true) {
      if (!layoutNodes.length) return;
      const vpWidth = viewport.clientWidth;
      const vpHeight = viewport.clientHeight;

      let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
      layoutNodes.forEach(n => {
        minX = Math.min(minX, n.x);
        maxX = Math.max(maxX, n.x + n.width);
        minY = Math.min(minY, n.y);
        maxY = Math.max(maxY, n.y + n.height);
      });

      const graphWidth = maxX - minX;
      const graphHeight = maxY - minY;
      const padding = 80;

      const scaleX = (vpWidth - padding * 2) / graphWidth;
      const scaleY = (vpHeight - padding * 2) / graphHeight;
      const scale = Math.min(1.2, Math.max(0.3, Math.min(scaleX, scaleY)));

      transform.k = scale;
      transform.x = (vpWidth - graphWidth * scale) / 2 - minX * scale;
      transform.y = (vpHeight - graphHeight * scale) / 2 - minY * scale;

      applyTransform(smooth);
    }

    // Center on specific active nodes
    function centerOnNodes(nodeIds) {
      const targets = layoutNodes.filter(n => nodeIds.has(n.id) || Array.from(nodeIds).some(nid => nid.split(':').pop() === n.id.split(':').pop()));
      if (!targets.length) return;

      const vpWidth = viewport.clientWidth;
      const vpHeight = viewport.clientHeight;

      let avgX = 0, avgY = 0;
      targets.forEach(t => {
        avgX += t.x + t.width / 2;
        avgY += t.y + t.height / 2;
      });
      avgX /= targets.length;
      avgY /= targets.length;

      transform.x = vpWidth / 2 - avgX * transform.k;
      transform.y = vpHeight / 2 - avgY * transform.k;
      applyTransform(true);
    }

    // Update active highlight
    function highlightActiveNodes(nodeIds) {
      activeNodeIds = new Set(nodeIds);
      document.querySelectorAll('.node-card').forEach(el => {
        const nid = el.getAttribute('data-node-id');
        const isActive = activeNodeIds.has(nid) || Array.from(activeNodeIds).some(id => id.split(':').pop() === nid.split(':').pop());
        const isSelected = selectedNodeId === nid;
        const beacon = el.querySelector('.beacon');

        if (isSelected) {
          el.className = el.className.replace(/inactive-node|active-node/g, '').trim() + ' active-node ring-2 ring-indigo-400 border-indigo-400';
          if (beacon) beacon.classList.remove('hidden');
        } else if (isActive) {
          el.className = el.className.replace(/inactive-node|ring-2 ring-indigo-400 border-indigo-400/g, '').trim() + ' active-node';
          if (beacon) beacon.classList.remove('hidden');
        } else {
          el.className = el.className.replace(/active-node|ring-2 ring-indigo-400 border-indigo-400/g, '').trim() + ' inactive-node';
          if (beacon) beacon.classList.add('hidden');
        }
      });

      // Update edges
      document.querySelectorAll('.edge-line').forEach(line => {
        const src = line.getAttribute('data-edge-source');
        const tgt = line.getAttribute('data-edge-target');
        const isEdgeActive = (activeNodeIds.has(src) || Array.from(activeNodeIds).some(id => id.split(':').pop() === src.split(':').pop())) &&
          (activeNodeIds.has(tgt) || Array.from(activeNodeIds).some(id => id.split(':').pop() === tgt.split(':').pop()));
        if (isEdgeActive) {
          line.classList.add('active-edge');
          line.setAttribute('marker-end', 'url(#arrow-active)');
        } else {
          line.classList.remove('active-edge');
          line.setAttribute('marker-end', 'url(#arrow)');
        }
      });
    }

    // Minimap
    function updateMinimap() {
      const miniSvg = document.getElementById('minimap-svg');
      const miniVp = document.getElementById('minimap-viewport');
      if (!miniSvg || !miniVp || !layoutNodes.length) return;

      let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
      layoutNodes.forEach(n => {
        minX = Math.min(minX, n.x);
        maxX = Math.max(maxX, n.x + n.width);
        minY = Math.min(minY, n.y);
        maxY = Math.max(maxY, n.y + n.height);
      });

      const gw = Math.max(100, maxX - minX + 160);
      const gh = Math.max(100, maxY - minY + 160);
      const mw = 144;
      const mh = 96;
      const scale = Math.min(mw / gw, mh / gh);

      let dots = '';
      layoutNodes.forEach(n => {
        const nx = (n.x - minX + 80) * scale;
        const ny = (n.y - minY + 80) * scale;
        const nw = Math.max(6, n.width * scale);
        const nh = Math.max(3, n.height * scale);
        const cfg = typeConfig[n.type] || typeConfig.utility;
        const isActive = activeNodeIds.has(n.id);
        dots += \`<rect x="\${nx}" y="\${ny}" width="\${nw}" height="\${nh}" rx="2" fill="\${cfg.color}" opacity="\${isActive ? 1 : 0.4}"/>\`;
      });
      miniSvg.innerHTML = dots;

      // Viewport box
      const vpW = viewport.clientWidth;
      const vpH = viewport.clientHeight;
      const curX = (-transform.x / transform.k - minX + 80) * scale;
      const curY = (-transform.y / transform.k - minY + 80) * scale;
      const curW = Math.max(12, (vpW / transform.k) * scale);
      const curH = Math.max(12, (vpH / transform.k) * scale);

      miniVp.style.left = Math.max(0, Math.min(mw - 10, curX)) + 'px';
      miniVp.style.top = Math.max(0, Math.min(mh - 10, curY)) + 'px';
      miniVp.style.width = Math.min(mw, curW) + 'px';
      miniVp.style.height = Math.min(mh, curH) + 'px';
    }

    // Pan & Zoom Event Listeners
    viewport.addEventListener('mousedown', (e) => {
      if (e.target.closest('.node-card')) return;
      isDragging = true;
      dragStartX = e.clientX - transform.x;
      dragStartY = e.clientY - transform.y;
    });

    window.addEventListener('mousemove', (e) => {
      if (!isDragging) return;
      transform.x = e.clientX - dragStartX;
      transform.y = e.clientY - dragStartY;
      applyTransform(false);
    });

    window.addEventListener('mouseup', () => { isDragging = false; });

    let touchStartX = 0;
    let touchStartY = 0;
    viewport.addEventListener('touchstart', (e) => {
      if (e.target.closest('.node-card')) return;
      if (e.touches.length === 1) {
        isDragging = true;
        touchStartX = e.touches[0].clientX - transform.x;
        touchStartY = e.touches[0].clientY - transform.y;
      }
    }, { passive: true });

    window.addEventListener('touchmove', (e) => {
      if (!isDragging || e.touches.length !== 1) return;
      transform.x = e.touches[0].clientX - touchStartX;
      transform.y = e.touches[0].clientY - touchStartY;
      applyTransform(false);
    }, { passive: true });

    window.addEventListener('touchend', () => { isDragging = false; });

    viewport.addEventListener('wheel', (e) => {
      e.preventDefault();
      const rect = viewport.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;
      const mouseY = e.clientY - rect.top;
      const zoomFactor = e.deltaY < 0 ? 1.1 : 0.9;
      const newK = Math.max(0.25, Math.min(2.2, transform.k * zoomFactor));

      transform.x = mouseX - (mouseX - transform.x) * (newK / transform.k);
      transform.y = mouseY - (mouseY - transform.y) * (newK / transform.k);
      transform.k = newK;
      applyTransform(false);
    }, { passive: false });

    // Floating Button Controls
    document.getElementById('btn-zoom-in').onclick = () => {
      transform.k = Math.min(2.2, transform.k * 1.2);
      applyTransform(true);
    };
    document.getElementById('btn-zoom-out').onclick = () => {
      transform.k = Math.max(0.25, transform.k * 0.8);
      applyTransform(true);
    };
    document.getElementById('btn-fit').onclick = () => fitView(true);
    document.getElementById('btn-dir').onclick = () => {
      currentDirection = currentDirection === 'TB' ? 'LR' : 'TB';
      document.getElementById('dir-label').innerText = currentDirection;
      computeLayout(currentDirection);
      renderGraph();
      fitView(true);
    };

    window.focusNode = function(nid) {
      selectedNodeId = nid;
      highlightActiveNodes(new Set([nid]));
      centerOnNodes(new Set([nid]));
    };

    // Parallax Scroll Spy
    const pane = document.getElementById('narrative-pane');
    const cards = document.querySelectorAll('.chapter-card');
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          cards.forEach(c => c.classList.remove('active-card'));
          entry.target.classList.add('active-card');
          const idx = parseInt(entry.target.getAttribute('data-index'));
          const activeChap = STORY.chapters[idx];
          if (activeChap) {
            selectedNodeId = null;
            document.getElementById('current-chapter-indicator').innerText = 'Chapter ' + activeChap.chapterNumber + ' Focus';
            const nodeLabels = (activeChap.activeNodes || []).map(n => n.split(':').pop()).join(', ') || 'Global';
            document.getElementById('active-nodes-list').innerText = nodeLabels;

            const activeSet = new Set(activeChap.activeNodes || []);
            highlightActiveNodes(activeSet);
            centerOnNodes(activeSet);
          }
        }
      });
    }, { root: pane, threshold: 0.45 });

    cards.forEach(c => observer.observe(c));

    // Initialize Layout & Graph
    computeLayout('TB');
    renderGraph();
    setTimeout(() => {
      fitView(false);
      if (cards[0]) {
        cards[0].classList.add('active-card');
        const firstChap = STORY.chapters[0];
        if (firstChap) {
          const firstSet = new Set(firstChap.activeNodes || []);
          highlightActiveNodes(firstSet);
          centerOnNodes(firstSet);
        }
      }
    }, 100);
  </script>
</body>
</html>`;
}
